### ISSUE TITLE
Linux環境; バックグラウンド実行すると動作が停止する

### ISSUE THREAD

**Issue by hn-yamada** [kumaryu/peercaststation#105]
バックグラウンド実行すると動作が停止したので報告します。
フォアグラウンドからバックグラウンドへ移しても停止しましたので、
バッググラウンドへ移すと停止する様です。

・コマンド
```
~/PeerCastStation-1.6.0$ mono PeerCastStation.exe &
[1] 6402
~/PeerCastStation-1.6.0$ jobs
[1]+  停止                  mono PeerCastStation.exe
```
・環境
PeercastStation: 1.6.0
OS: Debian 7.1 
Mono: 2.10.8.1 (Debian 2.10.8.1-8)

**Comment by kumaryu** [comment]
ずいぶん昔のにコメントしちゃいますが、デーモン動作できるpecastationdを作ったのでそれを使ってください、ということで閉じときます。
