### ISSUE TITLE
PCP Relayが異常な挙動をする

### ISSUE THREAD

**Issue by scottle** [kumaryu/peercaststation#107]
環境：Windows 7 SP1
　　　 PeCaSt 1.6.0
　　　 pcwmp

PCP Relayが0kbpsと1000kbps以上を繰り返して、数十秒後に下流を切断してしまう。
設定で最大上り帯域が600kbpsになっています。

![pacast1](https://f.cloud.github.com/assets/1718105/1368167/992b2720-3985-11e3-8070-9f80d1802ceb.jpg)
![pacast2](https://f.cloud.github.com/assets/1718105/1368169/9998690c-3985-11e3-87d3-b29d566a289f.jpg)
![pacast3](https://f.cloud.github.com/assets/1718105/1368168/99503bfa-3985-11e3-93fc-33fc61415ddc.jpg)

**Comment by kumaryu** [comment]
すごい今更ですが、上流側の送信の問題の可能性もあるのと、だいぶ古いバージョンなので閉じちゃいます。また似たような問題あれば上げてください。
