### ISSUE TITLE
wmv配信でパケットがループする

### ISSUE THREAD

**Issue by niwakazoider** [kumaryu/peercaststation#133]
以前flvで起きていたループ現象がwmv配信でも確認されました。上流にバージョン1.5.3より前のクライアントがいたかどうかは不明。再接続すると正常に受信できるようになりました。

**Comment by niwakazoider** [comment]
配信終了したチャンネルをリレーし続けていました。バージョンは2.3.2でしたがデータが流れているのでおそらくタイムアウトしないと思います（全員が2.3.3以上にすれば解決？）。上流は2.2.0でした。
![ss20161023](https://cloud.githubusercontent.com/assets/1770418/19621203/b167478e-98c7-11e6-97a3-d27c7b44f95d.png)

**Comment by kumaryu** [comment]
リレーのループかなぁ……
なんかループチェックできるといいですね

**Comment by niwakazoider** [comment]
該当バージョンが利用されなくなったためか、ループを見なくなったので閉じます
