### ISSUE TITLE
GUIよりストリームURLをコピーしようとすると異常終了する(1.7.9.1)

### ISSUE THREAD

**Issue by nanashisami** [kumaryu/peercaststation#156]
ST1.7.9.1にて
GUIを開き、リレー情報からchのストリームURLをコピーしようとするとSTが異常終了する場合があります。

環境は以下
OS：Win7Pro 64bit
CPU：i7-2600K
メモリ：16G

**Comment by kumaryu** [comment]
d3d78e23 で対策入ってたので閉じます。
1.8以降なら落ちはしません。
