### ISSUE TITLE
1.8.0 ヘルプファイルの画像リンク切れ

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#175]
settings.html から参照されている以下の画像ファイルが zip に同梱されておらず、リンク切れになっています。
images/gui_uisettings.png
images/gui_connectionsettings.png

**Comment by kumaryu** [comment]
67e50e245a4d3d47bc9e05fe5f2b075e17f2823b で直してありましたので閉じます。安定版にはそのうち……
