### ISSUE TITLE
tipに不正なフォーマットのアドレスが指定されると落ちる

### ISSUE THREAD

**Issue by konoiz** [kumaryu/peercaststation#181]
tipに不正なフォーマットのアドレス、具体的には[ ]で囲まれていないIPv6等が指定された時、
HTTPOutputStream.csのCreateTrackerUri(の中のUri)がUriFormatExceptionを投げて、異常終了します。
例: ttp://localhost:7144/pls/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA?tip=::1

とりあえず、単純にtry-catchするだけこの問題に対処でき、他に影響なさそうな事は確認できました
```patch
--- HTTPOutputStream.cs	2014-09-16 19:50:00.000000000 +0900
+++ HTTPOutputStream.cs.new	2014-09-16 19:51:33.000000000 +0900
@@ -200,7 +200,11 @@
       if (tip!=null) {
         var endpoint = ParseEndPoint(tip);
         if (endpoint!=null) {
-          return new Uri(String.Format("pcp://{0}/{1}", endpoint, channel_id));
+          try {
+            return new Uri(String.Format("pcp://{0}/{1}", endpoint, channel_id));
+          } catch (System.UriFormatException) {
+            return null;
+          }
         }
         else {
           return null;
```

YPがこのようなURIを生成することはまずないと思うので、影響はあまりなさそうですが、
配信の掲示板などにかかれると多少はありそうなので、報告しておきます。
\# 最初Twitterの方でv6云々言ってましたが、別にv6関係なかったです。ごめんなさい。

**Comment by kumaryu** [comment]
だいぶ遅くなりましたが修正したので次のリリースに入れます。
