### ISSUE TITLE
MONO環境からWMP系で再生できない配信がある

### ISSUE THREAD

**Issue by MoonLightRose** [kumaryu/peercaststation#194]
CentOS 6にMONOを入れ、PeerCastStationを動かしています。
気づいたのですが、配信者によって再生できないことがあります。

内容はWMPのエラーで
＝＝
別のコンピュータ上の共有フォルダー内に保存されているため、再生リストを開け
ません。可能であれば再生リストをローカル コンピュータ上の再生リスト フォル
ダーに移動させてください。
＝＝
PCWMPでは、単に準備完了となって読み込みません。

環境はいろいろ試し、
CentOS6 64bit
MONOは3.10.0から、3.4.0など複数のバージョン
PeerCastStationは、1.9.0.2～1.4.2くらいまでのバージョンまでそれぞれ。
です。

flv配信は、すべて再生でき、
wmv配信が、再生できるのとできないのがあります。

そこでいろいろ調べてみたのですが、
http://xxx.xxx.xxx.xxx:7144/pls/XXXXXXXXX?tip=xx.xx.xx.xx:7144
のような、プレイリストURLではダメな配信があって、
http://xxx.xxx.xxx.xxx:7144/stream/XXXXXXXXX.wmv
のように、ストリームURLであればすべての配信が再生できることに気づきました。

そこでもう少し調べてみると、
PeerCastStationから受け取っているプレイリストが
MONO環境と、Windows版で違うことがわかりました。

Windows版だと、文字コードがSJIS、改行コードがCRLF
CentOS+MONO版だと、文字コードがUTF8(BOMなし)、改行コードがLFでした。

この辺がCentOS+MONOにPeerCastStationをおいて、
WindowsのWMP環境で再生できない原因かなと思いました。

MONOや環境のせいな気もしますが、
何かうまくできる方法があれば教えていただけるか、
PeerCastStationの方で、何らかの対応をしていただけるとありがたいです。

**Comment by kumaryu** [comment]
07157ab9095fb54fa480e3219c2a9a1fc0c01ef0 で強制的にCP932で出力するようにしました。
次のリリースに入れます。
