### ISSUE TITLE
WMV、FLV関係なくCPU使用率が高い状態が続いたり、繰り返したりします。

### ISSUE THREAD

**Issue by lipari2000** [kumaryu/peercaststation#200]
#179 にてWMVでCPU利用率が20～26％になると報告しましたが、その後も経過を見続けていたところ、FLVでも発生していることが分かりました。FLVを視聴するリスナーが増えたので安定しない回線の人が相対的に増えたせいかもしれません。

バッファ中は高確率で20％を超えたままになりますが、10％以下で推移していることもあるのでバッファで必ず20％を越えるということではありません。
また、問題なく視聴が出来ている状態でもCPU使用率を見ると 20 → 0 → 19 → 0 → 25 → 0 → 10 → 0 → 18 → 0 → 14 → 0 → 24 となっていることがあります。この状態で再接続を繰り返しせばそのうち安定した枝に付いて0～2％で推移するようになります。恐らく回線の相性が悪いか、上流が不安定のどちらかだとは思いますが、IMではこのようなことが発生しないのでPeercastStationの問題であると思います。
頻度的には、再接続で安定してもしばらくすれば再発する配信もあれば、2時間連続で見続けても安定している配信もあります。上流次第です。配信を開いたときの確率だと5割くらいでしょうか。

上記のCPU利用率はWindows7 Pro 64bit SP1、AthlonII 640 x4（4コア）搭載のPCで視聴しているときの値です。Windows7 Starter、atom N550（2コア、4スレ）搭載PCで視聴していると50～60％になることがあります。

ここからは推測ですが安価なCeleron 1.6Ghz（1コア）搭載PCではCPU使用率が100％になっていると思われます。

**Comment by lipari2000** [comment]
配信を開いた直後に20％超えになった上流についてですが、PeercastStationのバージョンは関係ないようです。1.63と1.9.02で20％超えを確認しました。

バージョンが表示されない上流（恐らくPeercast VP/IM版）で開いた直後に20％超えがありました。それと配信途中で20％超えがありました。

大規模なバッファに遭遇していないので今後も様子を見る予定です。
データが集まったらまた報告に来ます。

**Comment by peercaster** [comment]
私も最近CPU使用率を観察していて、ペカステが異常にCPUを食うので、作者様の連絡先を探していました・・。
win7 64bit corei7 3770kで視聴中に常時ペカステが１５％もCPUを使用しております。
ハイエンドでこれなので、ほかの方はペカステを使うのはきつそうだ
しかも安定版とされる1.8.0です。
lipari2000さんのCPU使用率に関する推測は正しいと思います。

**Comment by kumaryu** [comment]
CPU使用率に関しては最近のCPUはコア毎にクロック変動もするので、15%とか20%行ってても、クロックが最低で張り付いてるうちの15%とか20%だったりするので、実際特に重いわけでもなかったりします。
使用率が高い場合はCPUのクロックが上がってるかどうかも確認してください。

**Comment by peercaster** [comment]
教えてくださってありがとうございます。
正常な動作だったのですね

**Comment by kumaryu** [comment]
いや、正常な動作かどうかはわかんないです。
クロックが上がっててCPU使用率もそこそこあれば異常な動作であると思います。
うちの環境で調べた時にはCPU使用率高いと思ってた時は単にクロックが下がってた時だったのでそれ以上調べられなかったんですが、もしクロックが上がっててさらにCPU使用率が高い状況があれば調べますのでまた言ってください。

**Comment by lipari2000** [comment]
上流がペカステ1.8.0でCPU使用率15～26％で推移しているのを確認しました。
見ている限りはバッファは無く、問題なく視聴出来ている状態であり、PeerstPlayerのFSP表示も変動は無く安定（FPS 29/29）していました。
この状態が1分続いた後、ペカステの再接続をクリックすると0～2％で安定するようになりました。

以上、今後も気づいたことがあったら報告します。

**Comment by niwakazoider** [comment]
私もCPU使用率が高い状態になることがあり、前から気になっていたのでちょっと調べてみました。
一度この状態になると、リレーを切断したり再生を停止したりしても負荷は高いままでした。なのでデータを受信している部分が原因である可能性が高いと思います。
そこでいくつかの箇所にログ出力するコードを追加してみたところ PCPSourceConnection.ReceiveBody() が１秒間に多い時で２万回実行されていました。
転送が間に合わないなどの理由で送受信が断続的に停止してる間、waitなしで全力ループしているのではないでしょうか？

**Comment by peercaster** [comment]
クロックの確認の仕方うんぬんがよくわからないのですが
最近ペカステでCPU使用率が３０～７０％とかに跳ね上がることがあったので、やっぱりどうしても気になって
バージョンを順番に落としていったら、１．７．３でCPU使用率がいつもの０％～５％くらいで安定するようになった。
１．７．４からCPUの動き方が一気にかわってるなぁ

**Comment by lipari2000** [comment]
上流がペカステ1.8.0.0
視聴中にCPU利用率が10～26％になっていましたが、バッファは無く普通に見れている状態が発生。
→ 30秒以上続いたので再接続ボタンをクリック
→ 上流がペカステ以外に変わり、CPU使用率が下がって安定


上流がペカステ以外（バージョン表示なし）
配信を開いた直後からバッファが発生し、22％～26％で推移
→ 2分ほど待ってみましたが変化が無かったため再接続ボタンをクリック
→ 上流が（ペカステ以外）に変わりCPU使用率が下がって安定


上流がペカステ以外（バージョン表示なし）
視聴中にバッファが発生し、23～26％で推移
→ 1分程待っていたら上流がペカステ1.8.0に変わってその後CPU利用率が下がって安定


上流がペカステ1.8.0.0
視聴中にCPU使用率23％になりましたが、直ぐにCPU使用率が下がる。
→ 1分程まってたら再びCPU利用率が高くなりましたが、直ぐに上流が違うIPアドレス（ペカステ1.8.0）に変わり、その後CPU利用率が下がって安定


上流がペカステ以外
視聴中にバッファ発生が発生し、23～25％で推移
→ 30秒程まったら安定 ※上流の変化なし
→ 1分程で再びバッファ発生 22～27％
→ 2分程で上流が（ペカステ以外に）変わって安定


バッファが発生したら必ずCPU使用率が高くなるわけではなく0～2％で安定していることもあります。

**Comment by plonk** [comment]
問題を再現できる環境にあると思うので、調べてみました。

1分間、peercast station を動作させてタスクマネージャ―で「CPU 時間」を計測しました。起動10秒後に、なるべく間断なく 875Kbpsから992Kbpsまでのビットレートの５つのチャンネルを開きました。（合計の帯域負荷は回線の限界を超えています）

オリジナルの 1.8.0 は2分0秒、一方以下の変更を加えた 1.8.0 は 1 秒でした。

PCPSourceStream.cs:

    public static IEnumerable<Atom> RecvAtoms(this StreamConnection connection)
    {
      var res = new Queue<Atom>();
    +  bool partial = false;
      connection.Recv(s => {
        while (s.Position<s.Length) {
          var pos = s.Position;
          try {
            var atom = AtomReader.Read(s);
            res.Enqueue(atom);
          }
          catch (System.IO.EndOfStreamException) {
            s.Position = pos;
    +        partial = true;
            break;
          }
        }
      });

    +  if (partial)
    +    connection.Recv(s => { throw new System.IO.EndOfStreamException(); });

      return res;
    }

この変更はストリームに不完全なアトムが残った場合に EndOfStream 例外を発生させて StreamConnection.Recv の中で recvEvent.Reset() を行わせることが狙いになっています。

なぜこれで負荷が減るのか、自分なりの説明をします。上の方が書いておられるように 1.7.3 ～ 1.7.4 の間にCPU使用量が変わっています。コミットを追って上記のようなテストしたところ、https://github.com/kumaryu/peercaststation/commit/3f587876d41e502bdeb06770fb8842407ddfd3f2 が原因のようです。

一見挙動を変えているようには見えないのですが、StreamConnection.Recv メソッドの仕様によって上層のループ（SourceConnectionBase.Run）の振る舞いが変わっているようです。

Recv メソッドは、AtomReader.Read などが発生させる EndOfStreamException をキャッチして、recvEvent.Reset() を行います。このことは Run メソッドのループの次のイテレーションが、新たなデータの到着（あるいはキューへコールバックが追加される）までブロックすることを意味しています。

ですが、RecvAtoms では EndOfStreamException をラムダ式内キャッチしていて（上に渡すとストリームが巻き戻されるのでこれも都合が悪い）、これが原因でブロックが行われず受信バッファには不完全なアトムしかないにもかかわらず、次のイテレーションにGOサインが出されているようです。

バッファに不完全なアトムがある場合に出る症状ですので、回線負荷や受信データの分割に左右される点が、この問題が再現しない環境がある理由かと思います。

**Comment by kumaryu** [comment]
ありがとうございます。 9e7786b522f4851678add1cf462134041bbee4bc で対処しました。
ちょっと手元で再現できてないんでアレですが……

**Comment by kumaryu** [comment]
とりあえずそれっぽいのは対処して開発版の1.9.1に入れたので一旦閉じときます。
まだだめそうなら再オープンするなり別にIssue立ててください。
