### ISSUE TITLE
リレー接続先の制御について

### ISSUE THREAD

**Issue by xmiyax** [kumaryu/peercaststation#209]
C#初学者で誠に恐縮なのですが、トポロジー制御のデモンストレーションに用いるため、新規リスナーからのリレーリクエスト要求時に接続先ノードをトラッカー側がある程度制御出来るような改変を加えようと考えています。
（あくまでデモで、従来とは違ったトポロジーを形成する、という部分を見せるのが目的なのでこの改変による実用性はほとんど考慮されていませんが）

ソースコードを読んで
PCPSourceStreamのCreateConnectionでsource_uriとtrackerURIに応じたSourceConnection処理

PCPSourceConnectionでHTTPヘッダ受け取り→ステータスに応じてPCPハンドシェイク

の処理は追えたのですがその前の、接続要求に対して
「自分のリレー数がいっぱいなら自分の子ノードへ回す」
の部分を探しているのですがIsRelayFullやIsRelayableを追っても
なかなか見つけることが出来ず、大変申し訳ないのですが
どこの部分でこちらの「自分のリレー数がいっぱいなら自分の子ノードへ回す」
に当たる処理を行っているか教えていただけないでしょうか。

Issue利用するのが初めてだったもので先ほど誤って記事投稿してしまい
焦ってcloseしてしまいました、重ね重ね申し訳ありません

**Comment by kumaryu** [comment]
PCPOutputStreamのIsRelayFullプロパティにリレーがいっぱいかどうかが格納されてます。
これはPCPOutputStreamのコンストラクタで判定して設定しています。
次に接続するノード情報を送ってるのはPCPOutputStream.DoStop内ですが、
実際に送るノードを選択してるのはPCPOutputStream.SelectSourceHostsなのでこいつをいじれば次の接続先を制御できます。
