### ISSUE TITLE
配信側で行ったチャンネル情報の変更がリレーに反映されない

### ISSUE THREAD

**Issue by manukeno** [kumaryu/peercaststation#210]
配信中に配信者がチャンネル情報（例えば概要やコンタクトURLなど）を変更しても、視聴者側がpeercastから見ることのできるチャンネル情報が更新されない現象があります。
掲載先YPのチャンネル情報は更新されます。

検証環境
 配信側: peercaststation 1.9.0.2
 視聴側: peercast IM0045

**Comment by kumaryu** [comment]
実はそもそも実装されてなかったのに気付きました。
c614f2e66906097f0096f29f6fbb9ff3828c613c で実装したので次のリリースに入ります。
