### ISSUE TITLE
mono で、接続のクリーンアップに関するパフォーマンス問題

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#214]
FreeBSD 10.1 (VirtualBox)上での再現が最も簡単で、HTML UI を開くだけで負荷が高くなり、事実上操作できなくなります。

![freebsd](https://cloud.githubusercontent.com/assets/1680210/6073650/5c99fc2a-adf4-11e4-8531-4854d4886bff.png)

Windows 上では、ローカルの Expression Encoder をソースにチャンネルを10個ほど作成し、HTML UI のリレー画面で接続一覧とリレーツリーの表示を展開します（API呼び出しを増やすことが目的）。
この時点でけっこうな負荷になるのですが、次にエンコードを開始し、しばらくしたら終了すると負荷が非常に高くなります。

![windows](https://cloud.githubusercontent.com/assets/1680210/6073649/5c93c03a-adf4-11e4-8fbd-ae9a6eacab07.png)

Windows で高い負荷の時には StreamConnection の CleanupSend で数百ミリ秒単位の時間がかかっていました。

    private void CleanupSend()
    {
      if (outputStream==null) return;
      IAsyncResult sending_result;
      do {
        lock (sendLock) {
          sending_result = sendResult;
        }
        if (sending_result!=null) {
          if (!sending_result.AsyncWaitHandle.WaitOne(sendTimeout)) {
            break;
          }
        }
    +    Thread.Sleep(10);
      } while (sending_result!=null);
    }

上のように 10 ミリ秒のスリープを挟んでみると FreeBSD、Windows 共に負荷が高くならなくなりました。
ログを取ると、ループを150回まわって 1500 ミリ秒費やしているような場合もありますので、実時間はそれなりにかかるようです。

FreeBSD の mono のバージョン:

    Mono JIT compiler version 3.10.0 (tarball Wed Jan 28 06:30:53 UTC 2015)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
            TLS:           __thread
            SIGSEGV:       altstack
            Notification:  kqueue
            Architecture:  amd64
            Disabled:      none
            Misc:          softdebug
            LLVM:          supported, not enabled.
            GC:            sgen

Windows の mono のバージョン:

    Mono JIT compiler version 3.12.0 (Visual Studio built mono)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
            TLS:           normal
            SIGSEGV:       normal
            Notification:  Thread + polling
            Architecture:  x86
            Disabled:      none
            Misc:          softdebug
            LLVM:          supported, not enabled.
            GC:            sgen

**Comment by kumaryu** [comment]
sendResultが完了してるけどnullにならないから無限ループしちゃうやつだこれ……
Sleep(10)入れてもたぶんどんどん無限ループするスレッドが増えちゃうのでまずいです
調べてみます

**Comment by kumaryu** [comment]
1c666221d6a716e8aff310591556fe022a9b3a6d で対処したので安定版の2.2に入ります。
近々出す開発版の2.3だともう該当のコードがないので起きないといいなぁ
