### ISSUE TITLE
HTML UI で配信開始時に履歴が追加されない

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#215]
ビットレートを入力せずに配信を開始するとチャンネルは作成されるのですが、配信設定履歴に項目が追加されません。ブラウザの開発ツールで見てみると addBroadcastHistory の呼び出しに対してエラーが返っています。

![req](https://cloud.githubusercontent.com/assets/1680210/6090858/b76296f0-aece-11e4-9f4c-991ad73ba3ce.png)

![res](https://cloud.githubusercontent.com/assets/1680210/6090857/b761605a-aece-11e4-9701-f464a4bf3177.png)

どうやら bitrate が空文字列だった場合、JToken → int のキャストでエラーになるようです。

relays.js の 277行目以降を以下の様に変更すると追加されました。

    PeerCast.addBroadcastHistory({
      yellowPage: self.yellowPage() ? self.yellowPage().name : null,
      streamType: sourceStream,
      contentType: contentReader,
      streamUrl: self.source(),
    -  bitrate: self.infoBitrate(),
    +  bitrate: Number(self.infoBitrate()),
      channelName: self.infoName(),
      genre: self.infoGenre(),
      description: self.infoDesc(),
      comment: self.infoComment(),
      contactUrl: self.infoUrl(),
      trackTitle: self.trackName(),
      trackAlbum: self.trackAlbum(),
      trackArtist: self.trackCreator(),
      trackGenre: self.trackGenre(),
      trackUrl: self.trackUrl()
    });

**Comment by kumaryu** [comment]
d1e74826ac9f6f158be0edee12d84eb8943e8264 で対応しました。
他にもあやしい値をぶちこむとエラー出すところと無視してスルーするところがあったので、なるべくエラー出すように統一しておきました。
