### ISSUE TITLE
 PeerCastStation all versions (include Version 1.9.1) can not work? 

### ISSUE THREAD

**Issue by hfmanly** [kumaryu/peercaststation#216]
I use PeerCastStation of all versions,but no one can work when I click the Play button in page of http://temp.orz.hm/yp/, but the peercast can work. why? 

it shows: 
![image](https://cloud.githubusercontent.com/assets/4994187/6426178/52e65e8a-bf88-11e4-8b2d-eae3c53bb6c1.png)

thanks

**Comment by progre** [comment]
It may be that your PeerCastStation can't receive TCP 7144.
You should check that your router is routing TCP 7144.

**Comment by kumaryu** [comment]
Fixed by 49954e588ffbc8c3f23495ae7de872b82fc10e53
