### ISSUE TITLE
WMV配信のプレイリストファイルの要望

### ISSUE THREAD

**Issue by shinji3** [kumaryu/peercaststation#217]
asxのプレイリストファイルって対応してないプレイヤーが多い
VLCもmpvも対応していないから引数を工夫しなきゃいけない
wmv配信のプレイリストファイルってm3uじゃダメですか？
古い形式のxml形式じゃないasxファイルならVLCでもmpvでもWMPでも開けます。
http://support.microsoft.com/kb/170909/ja

**Comment by shinji3** [comment]
VLCはasx形式に対応していましたけど、utf-8じゃないと認識してくれませんでした。
MacのVLCは大丈夫ならしいですけどWindowsのVLCは駄目でした。
古い形式のxml形式じゃないasx形式はVLCの場合は拡張子がasx形式だと認識してくれませんでした。
拡張子がplsとかiniだと認識してくれましたが、この拡張子だとWMPで開けなくなりました。

**Comment by kumaryu** [comment]
c70b134be2dbaf9729422c2a5e369c9eaf0722e2 でプレイリストのURLにおいてチャンネルIDの後ろの.m3uをつけると強制的にm3uで落とせるようにしました。
たぶんこれじゃあんまり役に立たないので、そのうち標準のプレイリスト形式を設定できるようにします。

**Comment by shinji3** [comment]
拡張子だとPeCaRecoderでプレイヤーの設定をしたときに
"$x.m3u"
を指定すると
http://localhost:7144/pls/FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF?tip=255.255.255.255:7144.m3u
になって再生できませんでした
"http://$z/pls/$1.m3u?tip=$2"
だと上手く再生できましたがpcypLiteだと$zとか無いので設定できません。

拡張子では無くクエリ文字列なら上手くいきそうな気がします
たとえば
"$x&pls=m3u"
と指定すると
http://localhost:7144/pls/FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF?tip=255.255.255.255:7144&pls=m3u
になるし
pcypLiteでも
"<stream/>&pls=m3u"
という指定でいけそうです

**Comment by kumaryu** [comment]
クエリで指定する方が自然だし便利そうなので
928e7d44af72f4aa40c394dd3f2f92fdc4c95006
でその形式にしました。
2.1.4に載せます。
