### ISSUE TITLE
1.9.2 の zip 版にYPブラウザのヘルプが含まれていない

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#221]
PeerCastStation-1.9.2.zip に help/ypbrowser.html が含まれていないため、
HTML UI の「ヘルプ」から「YPブラウザ」をクリックするとリンク切れになります。

**Comment by kumaryu** [comment]
7c02b783f9ff7c1a3f5b743e7502fe5f6f7e34b8 で修正しました。たぶん。
