### ISSUE TITLE
PCPハンドシェイクを行わない接続を生かしてしまう

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#227]
クライアントがHTTPでリレー要求した後、PCPハンドシェイクを行わずにコネクションを張ったままにすることができます。バージョンは、1.9.2 と 1.8.1 で確認しました。

最近、複数の配信で配信者の直下に同一IPの接続が多数出現して、YPに報告されるリレー数が不自然に増えるということがありましたが、これが原因ではないでしょうか。

また、意図的にそのような接続を多数張るスクリプトを動かすと、PeCaSTのCPU使用率を上げることができます。

![connection_flood](https://cloud.githubusercontent.com/assets/1680210/11101083/4d6a77fe-88f8-11e5-8967-30744b3fc4bd.png)

**Comment by aspennn** [comment]
これIssue立てようとして忘れてたやつ
IM版ではコネクションの上限(デフォルトだと50)
タイムアウトがあって、30秒でした

**Comment by kumaryu** [comment]
タイムアウト30秒は大きすぎてあんまり解決にならない気もする。
Handshakeはすぐやれってことで1秒か3秒程度にしようかと思います。
1秒だと短いかなぁ

**Comment by kumaryu** [comment]
c42095c064a3ff830738e5d936580ca374d00b4a でとりあえず3秒間ハンドシェイクが行われなければ切るようにしました。
