### ISSUE TITLE
2.0.0に更新してからリレー接続に時間がかかる、異常に重くなる

### ISSUE THREAD

**Issue by newbieasdf** [kumaryu/peercaststation#234]
開発ありがとうございます、いつも利用させて頂いています。
タイトルの通りなのですが、以前使っていた1.8.1に戻しても解決しないので投稿させて頂きます。
また、症状としてリレーツリーをみると　×***.***... (自分のip)となっておりリレーできていない状態です。
pcypを使用しているのですが、yellowpageの更新にも異常な時間とPcへの負荷がかかっています。
それとこちらの確認不足ですいませんが、peercaststationをブラウザから開いた際、情報のタブが

ポート開放	NG
リレー可能アドレス	***.***.***.**
リレー可能アドレス(LAN内)	***.***.***.**:****
視聴可能アドレス	無し
視聴可能アドレス(LAN内)	***.***.***.**:****

となっております。
ポート開放はできていることを確認しています。（peercast stationのツールから開放確認もからもできています。）
視聴可能アドレスは元から　無し　であったかは確認できていません。

OSはwindows7　バージョン6.1(ビルド 7601 service pack1)
.NET frame work  4.5.2
視聴使用ソフト pcyplite pcwmp

OutputListener: 2015-12-19T20:36:26 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:51325
OutputListener: 2015-12-19T20:36:30 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:51329
APIHostOutputStream: 2015-12-19T20:36:30 [APIHostOutputStream:127.0.0.1:51322] INFO  - IOException 受信エラーが発生しました
   場所 PeerCastStation.Core.StreamConnection.RethrowExceptions()
   場所 PeerCastStation.Core.OutputStreamBase.DoProcess()
APIHostOutputStream: 2015-12-19T20:36:30 [APIHostOutputStream:127.0.0.1:51322] INFO  - EndOfStreamException ストリームの末尾を越えて読み取ろうとしました。

他の方のissueを拝見したところこのエラー自体でても問題はないようですが、でていたので貼っておきます。
frame workの更新がはいってから重くなったと感じ復元してみましたが変わりませんでした。

**Comment by kumaryu** [comment]
リレー接続に時間がかかるのは、ポート開放確認が上手くいってないからだと思われます。
そもそもそんなに重いのはなんだろうなぁ。
セキュリティソフトとか何使ってますでしょうか？

**Comment by newbieasdf** [comment]
早い返信ありがとうございます。
nifty社？の常時安全セキュリティ24というものを使っています。http://www.nifty.com/sec24/service/safety.htm

たしかにセキュリティソフトが邪魔をしているようでした。
offにしてみると問題が解決されました。

**Comment by kumaryu** [comment]
見た感じカスペルスキーっぽいですね。
こっちでなんとかできそうな気もしないんですが情報を集めてみます。
カスペルスキーはスレッド立ち上げがめっちゃ時間かかるとか聞いたような……

**Comment by newbieasdf** [comment]
夜遅くにすいません、セキュリティソフト設定をいじってました。
どうやらストリーミングに対して常にウイルススキャンを行っていたようです。
その為、スキャン立ち上げで高負荷、その後もアップロードを制限し続けていたようです。
peercast stationに関しては以前、設定しスキャンを行わないようにしていましたが、pcyp lite pc wmpに対して今回スキャンを行っていた様でした。

セキュリティソフトの問題なんて最初に見直すべきところでしたし、情報が少ないソフトだと思うのでお手数をおかけしました。

**Comment by kumaryu** [comment]
ありがとうございます。設定で外せるならよかったです。
情報ありがとうございました。
解決はしたようなんで閉じときます。
