### ISSUE TITLE
2.1.2でポートが開いてないと認識される

### ISSUE THREAD

**Issue by vivivi1900** [kumaryu/peercaststation#238]
2.1.2でポートを開けてるのに開いてないと（表示上だけかもしれませんが）認識されます。

ルーターはYAHOOBBトリオモデム３G（ADSL）です。
http://ybb.softbank.jp/support/connect/adsl/spec/t3g.html

2.1.1の時
![2015-12-30 25](https://cloud.githubusercontent.com/assets/10167379/12051683/0969285c-af4a-11e5-842f-9f3dd94e3d93.png)

2.1.2の時
![2015-12-30 26](https://cloud.githubusercontent.com/assets/10167379/12051619/88a72eb2-af49-11e5-8eb0-9a18c69ffa02.png)

**Comment by kumaryu** [comment]
#241 と同じだと思われます。
65100d1a2d52c858e6648f0ae3be19830ac8799e で修正したつもりです。
間も無く2.1.3をリリースするつもりなのでそれで確認してください。

**Comment by vivivi1900** [comment]
2.1.3で、YahooBB トリオモデム3-G plusでポート解放、確認しました。
対応ありがとうございます。
