### ISSUE TITLE
http://www.pecastation.org/ の特徴表記が現在のものと違う

### ISSUE THREAD

**Issue by Philmist** [kumaryu/peercaststation#239]
> - Open Broadcaster SoftwareなどRTMP配信に対応したエンコーダからFLV配信が行えます(開発版のみ)

とありますが、現在は安定版でもRTMP配信が出来るので修正して欲しいです。

**Comment by kumaryu** [comment]
修正しました。
サイトのソースは gh-pages ブランチにあるので、今後は変更してプルリクエスト投げてもらってもかまいません。
