### ISSUE TITLE
HTML UIでIPv6 Anyの視聴設定が出来ない / GUIで設定しているとHTML UIを開いた瞬間にクラッシュする

### ISSUE THREAD

**Issue by Philmist** [kumaryu/peercaststation#240]
ほぼタイトル通りです。

GUIの"詳細設定→接続待ち受け"からIPv6 Anyを追加することでIPv6のアドレスで視聴することが可能になりますが、この設定をした上でHTML UIを開くと例外を出さずに動作を停止します。

OSはWindows 10でWindows Updateは全ての更新を適用した状態です。

**Comment by kumaryu** [comment]
少なくとも現在の開発版2.1.4では再現できませんでした(Win8.1 Pro 64bit)
まだ起きるようでしたら10でも試してみます

**Comment by Philmist** [comment]
確かにクラッシュしないですね…

別の些細なバグが検証中にみつかりましたが、このIssueはcloseして別なIssue立てます。
