### ISSUE TITLE
v2.1.2からpcypLiteと同時終了できない

### ISSUE THREAD

**Issue by voidst** [kumaryu/peercaststation#243]
pcypLiteと使用しています。
v2.1.2にアップデートしてから、タスクバーのpcypLiteを右クリック→終了→終了(完全)をクリックしてもpcypLiteと同時に終了しなくなりました。
タスクバーアイコン、プロセスともに残ったままです。
v2.1.1までは問題ありませんでした。v2.1.3にアップデートしてみましたが解決しておりません。

OS Windows7 64bit
pcypLite v1.8.1

**Comment by kumaryu** [comment]
c150bef3c36423d5058be31ff9ab1bc93f861d76 と
3fcd46541f5985b2a81351af8712f1043393456f で修正しました。
https://github.com/kumaryu/peercaststation/releases/tag/v2.1.x
にビルドしたやつを置いたので試してみてください。

**Comment by voidst** [comment]
v2.1.4にて解決しました。ありがとうございます。
