### ISSUE TITLE
接続設定の最大上り帯域について

### ISSUE THREAD

**Issue by MoonLightRose** [kumaryu/peercaststation#246]
接続設定にある、最大上り帯域のことですが、
現在これは、リレーだけでなくWAN側からのDirect接続もカウントされてしまいますが、
これで正しいのでしょうか。

その動作で正しいのであれば、要望なのですが、
リレーだけをみた帯域設定が出来るようにして欲しいです。

理由なのですが、
最近のチャンネルは数百kbpsから数Mbpsと、幅広いので、
単純に本数で決めるのはフェアじゃないかなと思いました。

そこで、チャンネル毎の帯域で本数を決めるために
チャンネル毎の帯域を設定してるのですが、
外のサーバーにPeerCastStationを置いているので、
pcwmpなどのダイレクト接続まで帯域にカウントされてしまいます。

それを複数台のPCや録画などで帯域消費してしまうと、
1本もリレーしていないのに、△になってしまい、
リレーが出来なくなるので、都合が悪いわけです。

もちろんいまの最大帯域の規定も△の算定に必要だと思うので、
残していかなければ行けないと思いますが、
もし問題が無く都合がよろしければ、
最大リレー上り帯域(合計/チャンネル毎)の項目も増やしていただけると嬉しいです。

＝＝
PeerCastSation 2.1.3
Cent OS 6.xのMONO 4.0.4環境と
簡単にですがWin 7 でも試しました。
＝＝

**Comment by kumaryu** [comment]
WAN側からの視聴も帯域計算に入れているのは仕様です。
実際に上り帯域を消費しているわけですから！
チャンネル毎の帯域制限は検討します。

**Comment by MoonLightRose** [comment]
そうですよね
お返事ありがとうございました。

要望の方は気持ちがお向きになりましたら、
よろしくお願いいたします。

**Comment by kumaryu** [comment]
一定数のリレー帯域を必ず確保するようにすると、リレー帯域が空いてても視聴分の帯域が足りない時に視聴ができないことになります。
それだと実用的に思えないので追加は見送ります。
帯域が足りないものは足りないので紫でも気にしないか、がんばって調整してください。
