### ISSUE TITLE
MKV配信でIMとのリレーがうまくいかない

### ISSUE THREAD

**Issue by mamekusari** [kumaryu/peercaststation#250]
ローカルでMKV配信を立てて、同一pcのimから再生。
ローカルでMKV配信を立てて、別のpcのimで再生。
ローカルでMKV配信を立てて、同一pcのim経由で別のpcのimで再生。
ローカルでMKV配信を立てて、同一pcのim経由で別のpcのpecastで再生。
yp上のMKV配信の直下をimで再生。
yp上のMKV配信の直下をpecastでとって、同一pcのimでリレーして再生。

これらのパターンで数十秒に一度くらいのペースで画像が崩れる現象が起きます。
間にあるpecastでも再生していましたが大きな問題はなかったのでimとのリレーに不具合があると思われます。

環境は配信立てたpcがwindows10 64bit pecast2.1.4 im50 ffmpeg2.8.6 64bit icecast2.4.3
別pcの方はwindows8.1 64bit pecast2.0.0 im50
再生ソフトはどちらもmpv2016-01-18 64bitです。

![snapshot_00 06_ 2016 02 16_00 56 05](https://cloud.githubusercontent.com/assets/6790856/13053578/9143bc4c-d448-11e5-8df2-12f1e1cfb4f1.jpg)

**Comment by kumaryu** [comment]
自分で取ればいいんですけどめんどいので聞いちゃいますが、
画像乱れたあたりでIM側で何かいつもと違うログ出ませんでしょうか。
出てればログを貼ってもらえると助かります。

**Comment by mamekusari** [comment]
imにも、というか本家にもログってあったんですね。
同一pcのimでそれっぽいログがとれました。
通常のimではSend skip: 1がたまにあるくらいでした。

Tue Feb 16 03:29:45 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:45 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:46 2016 [EROR] Send skip: 6
Tue Feb 16 03:29:47 2016 [EROR] Send skip: 3
Tue Feb 16 03:29:47 2016 [EROR] Send skip: 7
Tue Feb 16 03:29:50 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:50 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:58 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:58 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:58 2016 [EROR] Send skip: -64
Tue Feb 16 03:29:58 2016 [EROR] Send skip: 21
Tue Feb 16 03:30:09 2016 [EROR] Stream channel: 10054
Tue Feb 16 03:30:13 2016 [CHAN] Sent channel status update to 1 clients
Tue Feb 16 03:30:59 2016 [EROR] Incoming from 127.0.0.1:51759: Timeout
Tue Feb 16 03:31:03 2016 [EROR] Send skip: -64
Tue Feb 16 03:31:03 2016 [EROR] Send skip: -64
Tue Feb 16 03:31:08 2016 [EROR] Stream channel: 10054
Tue Feb 16 03:31:08 2016 [CHAN] Sending channel: HTTP 
Tue Feb 16 03:31:08 2016 [EROR] Send skip: 34667
Tue Feb 16 03:31:11 2016 [CHAN] Sending channel: HTTP 
Tue Feb 16 03:31:11 2016 [EROR] Send skip: 34848
Tue Feb 16 03:31:11 2016 [EROR] Stream channel: 10053
Tue Feb 16 03:31:16 2016 [EROR] Send skip: -64
Tue Feb 16 03:31:16 2016 [EROR] Send skip: -64

**Comment by kumaryu** [comment]
ありがとうございます。調べてみます。

**Comment by kumaryu** [comment]
MKVだと小さいパケットを沢山作って送っていたため、PeerCastStationでは小さいパケットが沢山送られてきても保持してられるのですが、PeerCastでは64個固定でしか持てないためパケットバッファが溢れて送信が間に合わず切れていました。
FLVでもあったことなので小さいパケットをなるべくまとめて送るように修正しました。
2bc14a33c239c7270686f8b3a0712d798e424a14
HTTP Push配信だけなので、近いうちにHTTP GET配信の方にも対応します。
次の開発版リリースにはのっけられると思います。
