### ISSUE TITLE
【要望】エラー通知について

### ISSUE THREAD

**Issue by scottle** [kumaryu/peercaststation#253]
PCPSourceConnection: 2016-02-28T03:55:35 [] ERROR - Server responses 404 to GET /9d0c41f8-bb6c-2f63-52f0-f4e7856ca5ba
PCPSourceConnection: 2016-02-28T03:55:40 [] ERROR - Server responses 404 to GET /9d0c41f8-bb6c-2f63-52f0-f4e7856ca5ba

上記のエラーは繋げられなくなった時に出てくるエラーだと思いますので、通知メッセージ以下にして頂けるとありがたいです。

**Comment by kumaryu** [comment]
4f4e33fda4c1467cf4d12ffb41b08f0cb991bafa で修正しました。
