### ISSUE TITLE
IPv6 Anyで待ち受けを追加したとき、HTTP UIでは"::"表示でわかりづらい

### ISSUE THREAD

**Issue by Philmist** [kumaryu/peercaststation#254]
詳細は以下の画像の通りです。

![temp](https://cloud.githubusercontent.com/assets/431640/13387366/40310ccc-def9-11e5-83b1-13e8c649edf2.png)

良くみないとわかりづらいですが、"IPv6 Any"と表示されるべきところが"::"表示になっています。
なお、GUIでは正しく"IPv6 Any"と表示されます。

**Comment by kumaryu** [comment]
自分でも確認してた時に発見したので直してました。
c7df84da36465c6b6e18c715aaef3e0b34b7a93a で直ってるので2.1.5に入ります。
