### ISSUE TITLE
PeerCastStation2.1.5.0 ヘルプの記述ミス?

### ISSUE THREAD

**Issue by gribbit** [kumaryu/peercaststation#258]
細かすぎてどうでもいいことかもしれませんが、ヘルプを読んでいて記述間違い？（**太文字部分**）などをいくつか見つけたので報告します。

/help/usage.html　使い方　--------------------------------------------------------------------------------------------
・設定（GUI編）
「未開放です」になった場合は使っているマシンに向けてポートが**開放されてりません**。

・設定（HTML UI編）
「未開放です」になった場合は使っているマシンに向けてポートが**開放されてりません**。

・配信を見る（HTML UI編）
新しく配信を見るのはPeerCastStation単体ではできません。
（ここはGUI編の配信を見るの項と記述が違うので一応報告です）

・自動リレー管理について
リレー要求されたチャンネルの下位リレーとして再リレー不可の**ノードにに**他の下位リレーのノード情報を送信する

/help/ypbrowser.html　YPブラウザ　----------------------------------------------------------------------------------
・YellowPageブラウザを開く
**YPブラウザいまのところ**HTML UIにしかありません。
（YPブラウザの後に’は’が抜けてる？）

・チャンネルを探す
検索との違いは上部のタブに表示されてワンクリックで切り替えできるのと、チャンネルの表示色を**設定できるることです。**

/help/broadcast.html　配信　------------------------------------------------------------------------------------------
・HTTP配信
配信開始ができない場合は**何ストリームURL**が正しいか、チャンネル名が入力されているかを確認してください。（ストリームURLの間違い？）

・RTMP配信
配信開始ができない場合は**何ストリームURL**が正しいか、チャンネル名が入力されているかを確認してください。（ストリームURLの間違い？）

/help/settings.html　設定　---------------------------------------------------------------------------------------------
・イエローページ
自分で配信をする際に**掲載するや**、YPブラウザでチャンネルを取得するイエローページを設定します。
（掲載するの後に'イエローページ'が抜けてる？）

「この記述であってるから！」というところもあるかもしれませんが、その時はごめんなさい。

**Comment by Philmist** [comment]
指摘部分を直してPR投げました。

**Comment by Philmist** [comment]
mdの方を修正するのでPRを一旦取りさげました。

**Comment by Philmist** [comment]
#260 でPR投げました。確認のほう、よろしくお願いします。

**Comment by kumaryu** [comment]
修正されたので閉じときます
