### ISSUE TITLE
安定版 v2.0.0 AirYPが使用できない

### ISSUE THREAD

**Issue by kinsato** [kumaryu/peercaststation#263]
安定版 v1.8.1以前の時はAirYPを使用して配信をすることが可能でしたが
v 2.0.0を使用するとAirYPに「error: peercast not found」のエラーが表示
されるようになってしまい配信が出来なくなってしまいました。

AirYPの設定状態とログを添付致します。

![airyp_setting](https://cloud.githubusercontent.com/assets/19618951/15625360/c297c536-24de-11e6-965a-a3375c74daea.png)

![airyp_log](https://cloud.githubusercontent.com/assets/19618951/15625379/780da8cc-24df-11e6-8b8d-6127dfd41c9b.png)

最新のバージョンでもAirYPが使用できるようになると嬉しいです。

**Comment by kumaryu** [comment]
たぶんセキュリティ強化のためAPI呼び出し仕様を変更したせいだと思われます。
対応はしたいと思いますがちょっと時間かかるかもしれません。
てかAirYPてまだ使ってる人居たんだ……

**Comment by kumaryu** [comment]
AirYPでPeerCastStationのチェックを外すとAirYPに載せられるところまでは確認しました。
視聴できるかどうかは確認できませんでしたがtipがおかしい気も？
それでいけるかどうか試してもらえませんでしょうか。古いペカステでも同じなので1.8.1などで試してもらってもかまいません。

**Comment by kinsato** [comment]
返信遅くなってしまいすいません。
チェックを外して視聴できるか時間を見つけて確認します。

**Comment by kinsato** [comment]
PeerCastStationのチェックを外し、ペカステv2.0.0で検証してみたところ
無事視聴できる事が確認できました。

ただ、自分の環境だけかもしれませんが
PeerCastStation→AirYPの順に起動し配信すると、チャンネルは載せられるが視聴ができない
AirYP→PeerCastStationの順に起動し配信すると、チャンネルも載せられるし視聴もできる
という現象がありました。

今回お忙しい中、快く相談に応じていただきありがとうございました。

**Comment by kumaryu** [comment]
真面目に対処するならAirYP側を修正しないとだめそうですね。
@niwakazoider に投げよう！

**Comment by kumaryu** [comment]
言ったら対処されました。AirYP 2.6.0を使ってください。
まあべつにPeerCastStationのチェック外せば無くても動くんですが。
