### ISSUE TITLE
Linux+mono環境 PeerCastStation2.3.1のメモリ使用量が増え続ける

### ISSUE THREAD

**Issue by gribbit** [kumaryu/peercaststation#268]
Linux+mono環境においてPeerCastStation2.3.1で配信を視聴しているとメモリ使用量が増え続けます。

一例としてはPeerCastStation起動時のメモリ使用量が50MBほどだったのが、視聴を始めて30分で180MB、60分で320MBまで増え続けました。
メモリ使用量の増加はWMV配信とFLV配信で確認しました。
未視聴時はメモリ使用量の増加はなく、いったん増加したメモリ使用量が減少することはないようです。
PeerCastStaion2.1.5ではメモリ使用量の急激な増加は起こっていませんでした。

![2016-07-08-225715_524x393_scrot](https://cloud.githubusercontent.com/assets/5526340/16691881/771e0132-4569-11e6-8ae6-0deeabfe054d.png)

この現象が起きた時のログを貼っておきます。
[exception.txt](https://github.com/kumaryu/peercaststation/files/355204/exception.txt)
[peercast.txt](https://github.com/kumaryu/peercaststation/files/355205/peercast.txt)

PeerCastStation 2.3.1 開発版
Lubuntu 14.04.4 LTS
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

PeerCastStationの開発ありがとうございます。いつも便利に使わせてもらっています。

**Comment by kumaryu** [comment]
OSXのmono 3.2.7で確認したところそこまでは増えませんでしたが、だいぶメモリ使用量が多いのは確認できました。(220MB程度で頭打ちになりましたが)
OSXでですがmonoの4.2.3で使ってる分には大して増えないのでmonoの新しいバージョン(4.0以降)で試してもらえるでしょうか。
Taskとか使いまくるように変更したのでだいぶ最近のmonoでないと怪しいと思われます。

**Comment by gribbit** [comment]
monoの4.4.1で確認したところ、メモリ使用量は増えなくなりました。
推奨どおり、なるべく新しいmonoを使うようにします。
このissueをクローズするかはあれくまさんにお任せします。

**Comment by kumaryu** [comment]
新しいので大丈夫そうならOKです。
ユーザが多い.NETならまだしも、古いmonoの処理系の問題にまでは対応しきれないので新しいのでお願いします。
2.3以降はmono 4以降で動きますってことにしよう。
