### ISSUE TITLE
v2.3.1で[要認証]設定時のBasic認証が通らない

### ISSUE THREAD

**Issue by megane-wo-gurun** [kumaryu/peercaststation#269]
v2.1.5からv2.3.1にアップデートしてからなのですが、
[WANからの接続を許可]の[要認証]で、設定したID/パスワードを入力してもBasic認証が通らなくなってしまったようです。

自分なりに調べてみましたが、ID/パスワードを照合するところの処理で、設定の値じゃなくて、
https://github.com/kumaryu/peercaststation/blob/master/PeerCastStation/PeerCastStation.Core/OutputListener.cs#L118
でGenerate()した値が参照されているみたいです。

**Comment by kumaryu** [comment]
IDとパスワードどころか一切の認証関係の情報がデフォルト値から変更できなくなってましたね……
7fa466858ce0561e2d73c2b2ee193410ea991346 で修正しました。
