### ISSUE TITLE
Linux+mono環境　長期間、一度も終了させないで視聴し続けると徐々にメモリ使用量が増えていく

### ISSUE THREAD

**Issue by enushi** [kumaryu/peercaststation#271]
起動時は約50MB、数時間視聴すると約200MBで一端おちつきます。
ですがその後、視聴している間は徐々に増えていき、1日で約数十MBのペースで増えていました。
マシンのメモリが500MBなので、1週間位起動しっぱなしにしているとメモリが一杯になりSwapを使い出しました。
この間、エラーログは1度も出ていません。 

2.0.0ではメモリの監視はしていませんでしたが、数ヶ月間起動しっぱなしにしてもswapしませんでしが、2.2.0では1-2週間で必ずメモリが一杯になりました。（3回試して毎回再現しました）
おそらく2.2.0で追加した機能が原因なんじゃないかと思います。

ちなみにこのマシンで動かしてる高負荷なプログラムはPeerCastStationくらいです。

<img width="640" alt="kidoujikan" src="https://cloud.githubusercontent.com/assets/1637138/17330413/ba436de8-5901-11e6-9c36-5854c76a542c.png">

<img width="1143" alt="htop" src="https://cloud.githubusercontent.com/assets/1637138/17330382/9de4fe50-5901-11e6-9acb-fc36d48e557b.png">

<img width="897" alt="discio" src="https://cloud.githubusercontent.com/assets/1637138/17330407/b28a4b12-5901-11e6-87fe-c957ce8ab1ff.png">

PeercastStaion 2.2.0 安定版
CentOS 7
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Sat Nov 28 12:20:13 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen

よろしくお願いします。

**Comment by kumaryu** [comment]
#268 で似たようなのがあったんですが、開発版とmonoの4.4あたりでは大丈夫なようです。
どっちか新しくして試してもらえないでしょうか

**Comment by enushi** [comment]
了解です。開発版＋mono4.4で様子をみてみます。

**Comment by enushi** [comment]
mono4.4.2 にしてメモリの問題解決しました。(60MB-80MBで安定)
2.3.2, 2.2.0両方とも数日観察してみましたが、問題ありませんでした。

mono 4系だったので#268とは別件かと思いましたが同件だったようです。
本件クローズいたします。失礼いたしました。
