### ISSUE TITLE
イエローページ掲載用URLに完全なURLが入力できない

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#273]
GUI の設定ダイアログでイエローページを追加するときに、「pcp://」を省略したURLを入力すると、pcp:// が補完されますが、pcp:// で始まる完全なURLを入力すると pcp://pcp// で始まる誤ったURLに補完されてしまいます。

再現方法：
同タブで、[追加]ボタンをクリックして新しい行を追加する。
追加された行の掲載用URLフィールドに pcp://hoge と入力する。
フィールドの外をクリックすると、pcp://pcp//hoge と補完される。

ビューモデルのセッターのロジックで、else が抜けているためフォールスルーしているようです。
https://github.com/kumaryu/peercaststation/blob/master/PeerCastStation/PeerCastStation.WPF/CoreSettings/SettingViewModel.cs#L312

**Comment by kumaryu** [comment]
89e896309206f64286a433d603304b22967ff07a で修正しました。
空に再設定できてもなかったのに気付いたのでそれもついでに直しました。
