### ISSUE TITLE
エンコーダーとのRTMP接続でNull参照例外

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#278]
まれにRTMPSourceConnectionでNullReferenceExceptionが上がってプロセスが落ちます。

落ちる行番号は、

RTMPSourceStream.cs:320
RTMPSourceStream.cs:333
RTMPSourceStream.cs:432

(行番号は https://github.com/plonk/peercaststation/blob/352d27fe5f6a9f1882bc6c7481ea96b061dfa5f3/PeerCastStation/PeerCastStation.FLV/RTMP/RTMPSourceStream.cs に対応しています。)

なのですが、それぞれ last_msg が存在しないのに type 1~3 のチャンクが送られてきた場合に当たるようです。

添付の exception.log は、おそらくスマートフォン環境から接続されている場合で、くりかえし再起動するペカステに接続を試みています。

これを見ると特定のソフトウェアが変なデータを送っていることが原因のように見えるのですが、OBSとの組み合わせでも一度落ちた経験があります。

添付のRubyスクリプトは、意図的にペカステを落とすデータを送り付けます。ペカステ 2.2.0 はこれで落ちますが、2.3.2 は落ちませんでした。

last_msg が存在しないチャンクストリームに type 0 以外のチャンクが送られるとプロトコル違反とみなして接続をリセットするパッチ(2.2.xブランチ用)が用意できます。

[exception.txt](https://github.com/kumaryu/peercaststation/files/416831/exception.txt)
[script.txt](https://github.com/kumaryu/peercaststation/files/416832/script.txt)

**Comment by kumaryu** [comment]
a404ed0e068166fbd0422c1a35596dbbf0052a9e で修正しました。
ffmpegやlibrtmpを見たところ、前のパケットを参照するタイプなのに前のパケットが無かった場合は全て0であると仮定していたので、それに合わせて前のパケットが無かったら0埋めのパケットを参照するようにしました。
