### ISSUE TITLE
Monoで自動切断機能が停止する

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#283]
結論から言うとおそらくmonoのバグなのですが、ある程度機序がわかったので書いておきます。

ChannelCleaner などのチャンネルモニターの処理は、AutoResetEvent のタイムアウト・コールバックで定期的に呼び出されますが、mono では不明な理由でコールバックがたまに timeout 引数が false になって呼び出されます。結果、イベントが Set されたようになって、コールバックが解除されます。

該当部分にデバッグプリントを挿入すると、

    private AutoResetEvent stoppedEvent = new AutoResetEvent(false);
    private   monitorThreadPool = null;
    private void StartMonitor()
    {
      monitorThreadPool = ThreadPool.RegisterWaitForSingleObject(stoppedEvent, (state,timed_out) => {
        if (!timed_out) {
          (new Logger(typeof(PeerCast))).Info("ChannelMonitors OnTimer STOPPED");
          monitorThreadPool.Unregister(stoppedEvent);
        }
        else {
          (new Logger(typeof(PeerCast))).Info("ChannelMonitors OnTimer");
          foreach (var monitor in ChannelMonitors) {
            monitor.OnTimer();
          }
        }
      }, null, 5000, false);
    }

次のようなログが取れます。

    PeerCast: 2016-08-27T10:10:02 [Threadpool worker] INFO  - ChannelMonitors OnTimer
    PeerCast: 2016-08-27T10:10:07 [Threadpool worker] INFO  - ChannelMonitors OnTimer
    PeerCast: 2016-08-27T10:10:12 [Threadpool worker] INFO  - ChannelMonitors OnTimer
    PeerCast: 2016-08-27T10:10:17 [Threadpool worker] INFO  - ChannelMonitors OnTimer
    OutputListener: 2016-08-27T10:10:20 [Threadpool worker] INFO  - Client connected 127.0.0.1:56552
    OutputListener: 2016-08-27T10:10:20 [Threadpool worker] INFO  - Client connected 127.0.0.1:56554
    PeerCast: 2016-08-27T10:10:22 [Threadpool worker] INFO  - ChannelMonitors OnTimer
    OutputListener: 2016-08-27T10:10:24 [Threadpool worker] INFO  - Client connected 127.0.0.1:56558
    PeerCast: 2016-08-27T10:10:27 [Threadpool worker] INFO  - ChannelMonitors OnTimer STOPPED

また、添付のプログラム [wait-handle-callback.txt](https://github.com/kumaryu/peercaststation/files/440586/wait-handle-callback.txt) は 1 つの AutoResetEvent に対して 3 つのコールバックを登録するものですが、.Net では `123123...` といつまでも表示されるのに対して、mono では数行表示したところで `...123[1: STOPPED][2: STOPPED]3[3: STOPPED][3: STOPPED]` などとなって停止します。

動作環境：

    $ uname -a
    Linux xubuntu-14 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ mono --version
    Mono JIT compiler version 4.4.2 (Stable 4.4.2.11/f72fe45 Fri Jul 29 09:58:49 UTC 2016)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
            TLS:           __thread
            SIGSEGV:       altstack
            Notifications: epoll
            Architecture:  amd64
            Disabled:      none
            Misc:          softdebug 
            LLVM:          supported, not enabled.
            GC:            sgen

**Comment by kumaryu** [comment]
Task使うと大丈夫ぽいのでそっちにしますか
なんだかWaitHandleの監視に失敗してる場合にtimeoutがfalseで来るっぽいんですが、
なんで監視に失敗してるのかは調べられてません。

**Comment by kumaryu** [comment]
b6fd625cd4c67c90cc9934946d2ff02c6781f503 で入れました。
一晩動かした限りではちゃんとチャンネルが消えてました。

**Comment by plonk** [comment]
こちらでもチャンネルが残らなくなりました。直ったようなのでクローズします。
