### ISSUE TITLE
開発版v2.3.2でプレイヤーが再生出来ないことがある。

### ISSUE THREAD

**Issue by MoonLightRose** [kumaryu/peercaststation#285]
主にflvとRTMPでの場合です。
PeerCastStationへの接続IP次第で、上手く再生出来ません。

○環境
PeerCastStation 2.3.2
Windows 7 と CentOS 7のMONO 4.2.x環境
プレイヤーはpcfpとpeerstplayerの両方で現象を確認
# 

○パターン1
・プレイヤーの接続設定 : RTMP
・ペカレコなどのPeerCastのIP設定 : 192.168.xx.xx:7144(グローバルIPなどでも)にしている。

flv配信につないだ結果：
PeerstPlayer側は「NetConnection.Connect.Failed」になり黒い画面で進まない。
pcfpでも、再生出来ず止まる。
本来プレイヤーはRTMPで接続出来ない場合、自動的にHTTPになるはずだけど
これの場合そうならずに、止まってしまう。

○パターン2
・プレイヤーの接続設定 : RTMP
・ペカレコなどのPeerCastのIP設定 : 127.0.0.1:7144もしくはlocalhost:7144にしている。

flv配信につないだ結果：
プレイヤーの通常動作で配信によって、RTMPかHTTPに自動切り替えで再生される。

○パターン3
・プレイヤーの接続設定 : HTTP
・ペカレコなどのPeerCastのIP設定 : 192.168.xx.xx:7144や127.0.0.1:7144など、どちらも

flv配信につないだ結果：
プレイヤーの通常動作で、HTTPで再生される。
# 

安定版PeerCastStation 2.2.0ではこのようなことにならず
通常通り再生出来ることが確認出来ています。

**Comment by kumaryu** [comment]
開発版でRTMP再生が死んでるのは把握しているので近いうちに書き直すつもりです。
VLCなんかだとVLCが死んだりするくらいにひどいので。

RTMPからHTTPに落ちないのはプレイヤー側の動作なのでなんともわかりません。

**Comment by MoonLightRose** [comment]
commit 600f85025fbcfe5107dc795da38992f6ff5f4b4d
にて修正されたことを確認

**Comment by kumaryu** [comment]
そういえば確認してませんでしたけど、直ってるならよかったです。閉じちゃいます
