### ISSUE TITLE
WEBの設定画面でPeercastStationが強制終了する

### ISSUE THREAD

**Issue by scottle** [kumaryu/peercaststation#293]
環境
OS：Windows 10
Pacastバージョン：2.2.0.0（安定版）
回線：フレッツ光東日本 -1Gbps（OCN）
CPU：Intel i7-4771
RAM：32GB
ルータ：PR-500MI

エラー内容
2016/10/27 23:56:16: PeerCastStation (OS:Microsoft Windows NT 6.2.9200.0, CLR:4.0.30319.42000)
System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:address
   場所 System.Net.WebClient.UploadDataAsync(Uri address, String method, Byte[] data, Object userToken)
   場所 System.Net.WebClient.UploadDataTaskAsync(Uri address, String method, Byte[] data)
   場所 PeerCastStation.UI.PCPPortChecker.<RunAsync>d__2.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.UI.PCPPortCheckerPlugin.<CheckAsync>d__5.MoveNext()
   --- 内部例外スタック トレースの終わり ---
   場所 PeerCastStation.UI.HTTP.JSONRPC.RPCMethodInfo.Invoke(Object receiver, JToken args)
   場所 PeerCastStation.UI.HTTP.JSONRPC.JSONRPCHost.ProcessRequest(JArray results, JToken request)
   場所 PeerCastStation.UI.HTTP.JSONRPC.JSONRPCHost.ProcessRequest(JToken req)
   場所 PeerCastStation.UI.HTTP.APIHost.APIHostOutputStream.OnIdle()
   場所 PeerCastStation.Core.OutputStreamBase.DoProcess()
   場所 PeerCastStation.Core.OutputStreamBase.MainProc()
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Threading.ThreadHelper.ThreadStart()
---> (内部例外 #0) System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:address
   場所 System.Net.WebClient.UploadDataAsync(Uri address, String method, Byte[] data, Object userToken)
   場所 System.Net.WebClient.UploadDataTaskAsync(Uri address, String method, Byte[] data)
   場所 PeerCastStation.UI.PCPPortChecker.<RunAsync>d__2.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.UI.PCPPortCheckerPlugin.<CheckAsync>d__5.MoveNext()<---
![web](https://cloud.githubusercontent.com/assets/1718105/19772937/b6d33e9c-9ca2-11e6-9345-cc1f3ddd9a09.jpg)

**Comment by kumaryu** [comment]
PeerCastStation.exe.config (もし実行ファイルがPeerCastStation.exeでなければ実行ファイル名.config)
ってファイルが実行ファイルと同じフォルダにありますか？

**Comment by scottle** [comment]
.configファイルがないです。
インストールフォルダ、ログフォルダともに

**Comment by kumaryu** [comment]
どうやって入れたものでしょう？

**Comment by scottle** [comment]
最初はZIP版で入れていましたが、後にインスト－ラ版で入れました。
そのときに.configがあったか忘れました。

**Comment by kumaryu** [comment]
何かの拍子に消えた可能性があるのでインストーラ版であれば修復してみてください。
プログラムの追加と削除でいつもアンインストールするようなところで修復が出てくるはずです。

**Comment by scottle** [comment]
了解しました。
ありがとうございました。

**Comment by kumaryu** [comment]
このあとどうでしたでしょうか？
音沙汰ないということはたぶん大丈夫だと思うので閉じてしまいますけど、
まだ問題あるようでしたら再オープンしてください。
