### ISSUE TITLE
HTTP Direct が重複して正常に接続されないことがある

### ISSUE THREAD

**Issue by gribbit** [kumaryu/peercaststation#295]
以前、開発版2.3.2.0で HTTP Direct が重複して正常に接続されないことがありました。その後は確認できず、こちらの環境によるものかなと思っていたのですが、開発版2.3.3.0でも同様のことが起きたので一応報告しておきます。

開発版2.3.3.0
![pecast](https://cloud.githubusercontent.com/assets/5526340/20070042/4d8639a8-a562-11e6-986b-236195678ed6.png)

開発版2.3.2.0
![peercast01](https://cloud.githubusercontent.com/assets/5526340/20070775/11b49980-a565-11e6-9af1-6966e710552a.png)

PeerCastStationの接続設定は2.3.2.0と2.3.3.0で同じだったと思います。
![pecast2](https://cloud.githubusercontent.com/assets/5526340/20069928/de313468-a561-11e6-96cf-9051e83f0926.png)

開発版2.3.2.0と2.3.3.0でこの現象が起きた時のログです。
[peercast1.txt](https://github.com/kumaryu/peercaststation/files/576299/peercast1.txt)
[peercast2.txt](https://github.com/kumaryu/peercaststation/files/576304/peercast2.txt)

PeerCastStation 2.3.3.0
pcypLite 1.9.4.0
Windows 10

**Comment by gribbit** [comment]
つい先日、Windows10の更新が始まり通信帯域を占有したとき時に報告したような現象（HTTP Directが重複し、その状況が改善せず配信に接続できない状況）が起こりました。
そこで帯域を絞って再現できるか試してみたところ、HTTP Directが重複する状況になりました。このときはしばらくすると重複が解消されたりと一時的な現象のようでした。

このissueとは全く関係がないかもしれませんが、もし原因が回線品質の問題であるなら不必要なデバッグの負担をお掛けしてしまうので一応報告しておきます。

**Comment by kumaryu** [comment]
#296 と同じような原因かなぁという気もしました。2.3.6で直したつもりなので一旦閉じときます。
2.3.6かそれ以降でまた出たら再オープンするか新しく報告おねがいします。
