### ISSUE TITLE
開発版V2.3.0以降で終了したチャンネルに視聴要求時にCPU使用率が100%近くになる。

### ISSUE THREAD

**Issue by MoonLightRose** [kumaryu/peercaststation#296]
Windows 7、開発版V2.3.4を含むV2.3.0以降で
終了したチャンネル(存在しないチャンネル？)へ接続要求がでると、確実にCPU使用率が100%近くになります。
リレー開始時とかではなくプレイヤーの接続要求時になると思います。
数秒たてば落ち着きますが、プレイヤーや録画の自動リトライなどがある場合はそのたびに100%近くになります。
安定版V2.2.0では問題が起きません。

一部ログを貼っておきます。
> OutputListener: 2016-11-22T04:56:21 [] INFO  - Client connected 127.0.0.1:17888
> OutputListener: 2016-11-22T04:56:24 [] INFO  - Client connected xxx.xxx.xxx.xxx:40171
> OutputListener: 2016-11-22T04:56:24 [] INFO  - Client connected xxx.xxx.xxx.xxx:40172
> WANConnectionService: 2016-11-22T04:56:24 [] INFO  - UPnP Action GetExternalIPAddress Success
> WANConnectionService: 2016-11-22T04:56:25 [] INFO  - UPnP Action AddPortMapping Success
> WANConnectionService: 2016-11-22T04:56:25 [] INFO  - UPnP Action AddPortMapping Success
> OutputListener: 2016-11-22T04:56:26 [] INFO  - Client connected 127.0.0.1:17894
> OutputListener: 2016-11-22T04:56:27 [] INFO  - Client connected 127.0.0.1:17896
> PCPSourceConnection: 2016-11-22T04:56:29 [] INFO  - IOException I/O エラーが発生しました。
>    場所 PeerCastStation.PCP.PCPSourceConnection.<ReadRequestResponseAsync>d__13.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.PCP.PCPSourceConnection.<ProcessRelayRequest>d__14.MoveNext()
> PeerCast: 2016-11-22T04:56:31 [WPF UI Thread] INFO  - IPv4 LocalAddress: 192.168.xxx.xxx
> HTTPOutputStream: 2016-11-22T04:56:36 [] INFO  - IOException 転送接続にデータを書き込めません: 既存の接続はリモート ホストに強制的に切断されました。。
>    場所 System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
>    場所 System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
>    場所 System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
>    場所 System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
>    場所 System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    場所 PeerCastStation.Core.ConnectionStream.<WriteAsync>d__52.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.HTTP.HTTPOutputStream.<SendResponseHeader>d__18.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.HTTP.HTTPOutputStream.<DoProcess>d__27.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext()
> HTTPOutputStream: 2016-11-22T04:56:36 [] INFO  - SocketException 既存の接続はリモート ホストに強制的に切断されました。
>    場所 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
>    場所 System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
> HTTPOutputStream: 2016-11-22T04:56:37 [] INFO  - IOException 転送接続にデータを書き込めません: 既存の接続はリモート ホストに強制的に切断されました。。
>    場所 System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
>    場所 System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
>    場所 System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
>    場所 System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
>    場所 System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    場所 PeerCastStation.Core.ConnectionStream.<WriteAsync>d__52.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.HTTP.HTTPOutputStream.<SendResponseHeader>d__18.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.HTTP.HTTPOutputStream.<DoProcess>d__27.MoveNext()
> --- 直前に例外がスローされた場所からのスタック トレースの終わり ---
>    場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext()
> HTTPOutputStream: 2016-11-22T04:56:37 [] INFO  - SocketException 既存の接続はリモート ホストに強制的に切断されました。
>    場所 System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
>    場所 System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
> OutputListener: 2016-11-22T04:56:40 [] INFO  - Client connected 127.0.0.1:17903
> OutputListener: 2016-11-22T04:56:40 [] INFO  - Client connected 127.0.0.1:17904
> OutputListener: 2016-11-22T04:56:40 [] INFO  - Client connected 127.0.0.1:17906
> OutputListener: 2016-11-22T04:56:40 [] INFO  - Client connected 127.0.0.1:17907
> OutputListener: 2016-11-22T04:56:40 [] INFO  - Client connected 127.0.0.1:17905
> OutputListener: 2016-11-22T04:56:41 [] INFO  - Client connected 127.0.0.1:17908

**Comment by kumaryu** [comment]
手元で簡単に試した感じでは再現できませんでした。
使ってるプレイヤーはなんでしょう？

**Comment by kumaryu** [comment]
#267 と同じなような気もしたのでコメントつけときます。

**Comment by MoonLightRose** [comment]
確かに #267 と同じに見えますね。

プレイヤーは、ちょっと前のことなのでハッキリとしてはいないのですが、
PeerstPlayerと、PeCaRecorderの録画機能と、言うことになると思います。

再現されないとのことですので、
また、改めて色々と試してみます。

**Comment by kumaryu** [comment]
2.3.5で直った可能性があるので試してもらえないでしょうか。
HTTP 404を返した時にContent-Typeを返してなかったのが問題だった可能性があります。
俺の手元では既にその修正入れたやつで試してたので発生してなかったのかも。

**Comment by aspennn** [comment]
2.3.5でも発生しました。
原因を探ったところ
HTTPOutputStream.WaitChannelReceivedのTask.Yieldで委譲するが
HTTPOutStream.DoProcessでawait WaitChannelReceivedしているせいで
タスクが完了(CancellationTokenSourceの10秒経つ)までループが発生しているからみたいです。

**Comment by kumaryu** [comment]
めんどくさいから適当にYieldで済ませちゃったところが悪さしてるぽいですね。
ありがとうございます。なんとかしてみます。

**Comment by kumaryu** [comment]
直しました！待ち方をちゃんと寝て待つようにしたので重くはならなくなりました。
ビルドされたやつは↓にあるので試してみてください。
https://ci.appveyor.com/project/kumaryu/peercaststation/build/artifacts

**Comment by MoonLightRose** [comment]
おいたままにしてて、すみません。

上記ビルドを試したところ、治っているようでした！
ありがとうございました。

**Comment by kumaryu** [comment]
2.3.6でリリースもしたので閉じときます。
