### ISSUE TITLE
要望　リレー管理時のGUI上IPの匿名化

### ISSUE THREAD

**Issue by AirSouthN** [kumaryu/peercaststation#299]
### 問題と期待される動作
現在の動き：配信中に意図せず他人のIPアドレス及び通信に使用されるTCPポートが晒されてしまう。
希望する動き：ハッシュ化やそれに準ずる物に変えてほしい。
### 再現方法
GUIを開きリレーツリーのタブを開く
### 動作環境
2.2.0.0

### 希望理由的な
IPアドレスやポートはルーター等でBANや共有する時に必要不可欠なものだと承知していますが、そういった事は日常的に発生するわけではありません。
とある配信上にて 意図せずに晒されたIPをリスナーがGOOGLE等で検索した所　2chの掲示板の書き込みがHITしたらしく それが掲示板にはられ軽いお祭り騒ぎに発展した、という事案が発生しました。
これ自体が大きな問題になる訳ではないですし、今まで出ていたものを今更と言った意見はあると思いますが、ニ○生やツイ○チ等の媒体と比較してもIPと言った個人に直接つながりかねないデータはでてませんし、隠す方向にシフトしたほうが良いのじゃないかと思った次第であります！

よろしければ、ご検討頂ければと思います。

**Comment by kumaryu** [comment]
開発版ですが2.3.6で対応しました。安定版にはそのうち……
