### ISSUE TITLE
開発版より安定版が先に更新されているのは何故？

### ISSUE THREAD

**Issue by lipari2000** [kumaryu/peercaststation#315]
開発版が更新されず、安定版に新機能が実装されていますが（新機能が実装されているように思えますが）、安定版のみになったんでしょうか。
それと更新された安定版を起動したままにしておくとメモリ消費量が増える（数百MB）というのを更新後に見かけます。
私は安定版を試していないのでメモリ消費量が増えるかどうか分かりません。

**Comment by kumaryu** [comment]
安定版の新機能ってのはポート開放チェック失敗時に未開放扱いになるってやつでしょうか？
単に更新タイミングの問題で開発版に入れられてないだけです。
起動したままでメモリ消費量が増えるのはちょっと試した感じでは再現できてなくて情報もほぼないのでよくわかってないです。

**Comment by lipari2000** [comment]
新機能についてはポート関連のことです。

メモリ消費量増加について、私は開発版を使っていますが問題はないです。

**Comment by lipari2000** [comment]
ここをCloseしてください。
今後は報告することはないと思います。

**Comment by kumaryu** [comment]
Closeは誰でもできませんでしたっけ。閉じときますけど

**Comment by lipari2000** [comment]
Issue作った人が閉じれるんですね、知りませんでした。
