### ISSUE TITLE
unblock.batにファイルの記載が足りない

### ISSUE THREAD

**Issue by kumaryu** [kumaryu/peercaststation#316]
### 問題と期待される動作
zip版に含まれるunblock.batにPeerCastStation.CustomFilter.dllが記載されていないので、
unblock.batを実行しても手動でPeerCastStation.CustomFilter.dllのブロックを解除しないと起動できない。
unblock.batの更新を度々忘れるので忘れないようにするべきでは？

### 再現方法
PeerCastStation 2.3.7.1のzip版を落としてきてエクスプローラで展開してunblock.batを実行する。

### 動作環境
* Windows 10 1703 x64
* .NET Framework 4.7
* PeerCastStation 2.3.7.1 zip版

**Comment by mozsh** [comment]
こんな感じでどうでしょうかね
更新する必要もなくなるでしょうし

```bat
@cd %~dp0
for %%i in (*.exe,*.dll) do (
echo. > %%i:Zone.Identifier
)
pause
```

**Comment by kumaryu** [comment]
それだと意図してないファイル(パッケージに入れてないけどそこにあるファイル)も解除されちゃうのでセキュリティ的によろしくないと思ったのです
でも手動で実行するものだしさすがに心配しすぎな気がしたんでべつにいいか

**Comment by mozsh** [comment]
なるほど、そういうことでしたか
おまかせします:wink:

**Comment by kumaryu** [comment]
76f25c646b3c9d64bbeb1ef0ecce386a7e635ea1 で全部解除するようにしときました。
