### ISSUE TITLE
ブラウザではポートOKだがGUIでポート未開放となる

### ISSUE THREAD

**Issue by sentou7144** [kumaryu/peercaststation#318]
### 問題と期待される動作
ブラウザで表示した時にはポートは開放されていますが、
GUIではポート未開放となってしまいます。
### 再現方法
不明
### 動作環境
Windows7 64bit版
* .NET Frameworkバージョン: 4.6
* PeerCastStationバージョン:2.2.1.0 zip版
* プレイヤー: pcyplite

**Comment by kumaryu** [comment]
発生頻度とかわかりますか？
毎回なるとかたまにだけなるとか

**Comment by sentou7144** [comment]
発生頻度としては、常に上記の状態となっています。

**Comment by sentou7144** [comment]
7145を接続待ち受けのポート番号にしてみたところGUI側でも開放できました。

**Comment by kumaryu** [comment]
基本的に動作同じはずなんですけどGUI側だけってのは不思議だなぁ
設定画面でのポートチェックが未開放になるってことでいいですよね？
起動時にもチェックしてるんですけど、起動後ちょっとした時にステータスバーのところはどうなるでしょうか
![image](https://cloud.githubusercontent.com/assets/394413/26320731/ee7864c6-3f5e-11e7-9503-ca1b9d7cdc0d.png)
ここの部分なんですけど。
あとUPnPを使ってるかどうかも教えてもらえると助かります。

**Comment by sentou7144** [comment]
![aaaaaaaa](https://cloud.githubusercontent.com/assets/28842047/26354218/a82c705c-3ffe-11e7-8a81-2451d44fa606.jpg)
7144の場合だと未開放になり、7145は開放と出ます。
UPnPは有効にしています。

**Comment by sentou7144** [comment]
![aaaaaaaa](https://cloud.githubusercontent.com/assets/28842047/26354330/1f338bc2-3fff-11e7-8343-9d79796f10b0.jpg)
ブラウザ側だと開放と出てます。

**Comment by kumaryu** [comment]
これもしかして実は2つ起動してないですかね？
ブラウザからだと先に起動してるペカステの表示を見てて、そいつが7144ポート使ってるから後から起動したやつが取れてないのかも。
起動してない(つもりの)状態でタスクマネージャの詳細タブを見てPeerCastStation.exeがないか、
無ければタスクマネージャのサービスタブを見てPeerCastStationServiceがないかを確認してください。

**Comment by sentou7144** [comment]
ご指摘の通りでした。二重起動状態になっていたサービス停止して解決しました。
いつもプログラムファイルフォルダではないところでzip版を解凍して管理していたので、
今回の更新でインストーラー版を間違って起動させてしまったためかと思われます。

**Comment by kumaryu** [comment]
解決して良かったです。
同じ物2つなら二重起動しないようになってるんですけど、
間違ってサービス版が動いてるとかは起動しないのも困るので
何かすぐ気付くような表示を入れようかと思います。
とりあえずこのIssueは閉じときます。
