### ISSUE TITLE
RTMP視聴時の送信チャンクサイズを大きくしてほしい

### ISSUE THREAD

**Issue by aki1-asr** [kumaryu/peercaststation#319]
### 問題と期待される動作
現状ではRTMP視聴時の送信チャンクサイズが128バイト固定になっているが、これを大きいサイズで送れるようにしてほしい。
(1280バイトとか。もしくは隠し設定でも良いので設定可能にしてほしい)

128バイトの場合ストリームが細かく分割されすぎるためEth/IP/TCPのオーバーヘッドが大きく、ペカステ => クライアント間の送信トラフィックがストリームの約1.4倍になってしまう。
また、パケットが多くなる分クライアントからのTCP/ACK応答も多くなり、HTTP視聴に比べると受信トラフィックも10倍程になる。
(おおよそ数十kbpsが数百kbpsになるくらい)

\# IPv6でVPN経由していたりすると更に色々ついて倍くらいになったりもします。

尚、OBS => ペカステへのRTMP送信は1514バイトが殆どだったため、少なくとも1459以上で送信している模様。
(ぐぐったら4096バイトという情報もあったが、公式ではないので未確認)

実装された場合のメリットっぽいもの

* ペカステをVPS等に設置しており、インターネット経由でRTMP視聴する時に帯域が節約できる
* 上記同様、自宅等にVPN接続してRTMP視聴する時に帯域が節約できる
* 細かい大量のパケットが減るので、多少負荷が下がる(かもしれない)

デメリット

* Set Chunk Sizeを正しく解釈しないプレイヤー等、相性で再生できない事があるかもしれない

### 再現方法
RTMP視聴可能なクライアントでFLVチャンネルを視聴
パケットが実際に183バイト(128 + 55※)になっているかどうかはWiresharkで確認
※14(Eth) + 20(IPv4) + 20(TCP) + 1(RTMP Header) = 55バイト

### 動作環境
* Windows 8.1, Enterprise, Windows 10 Pro(視聴クライアントのみ)
* .NET Frameworkバージョン: .NET Framework 4.5.2
* PeerCastStationバージョン: 2.3.7.1 ZIP版
* プレイヤー: mpv 2017-02-12 x64, VLC 2.2.3

**Comment by kumaryu** [comment]
b797595a7c9204108e10d77b0b42798710015c98 でとりあえず1536くらいにしてみました。
ちょっと大きいかな？
v2.3.8に入れといたので一旦閉じときます。
何か問題あれば再オープンなり新しいIssueたててください。
