### ISSUE TITLE
NullReferenceExceptionエラーが大量におきる

### ISSUE THREAD

**Issue by niwakazoider** [kumaryu/peercaststation#320]
チャンネル終了時にたくさんエラーが出力されたのでログを添付します
[log.txt](https://github.com/kumaryu/peercaststation/files/1087031/log.txt)

直接これと関係あるかわかりませんが、終了する前のリレーも不安定でした

***動作環境***
Windows10 64bit
PeerCastStation 2.3.6.0 zip版
プレイヤーはpcap

**Comment by kumaryu** [comment]
上流につながってないのに下流からホスト情報が流れてくると例外投げまくりそうだったので
f6a0bb22a85e53fb1c870bb7fe1558db02535140 でつながってない場合は無視するようにしました。
たぶんなおった。
