### ISSUE TITLE
HTTPフェッチが成功しない状態でチャンネルを停止すると再接続を繰り返す

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#325]
### 問題と期待される動作

WME などのエンコーダーが起動していない状態で、ソース「http」でチャンネルを作成すると、チャンネルを停止しても、`localhost:8080` などへの再接続を繰り返します。WME に接続できた場合は、チャンネル停止後の再接続は起こりません。

例えば HTTP Push Source チャンネルを作成するつもりで http チャンネルを作成したとします。http チャンネルを削除して HTTP Push Source チャンネルを作り直すと、どちらもソースURLが同じなので、PeerCastStation が自分自身に接続しに来て、エンコーダーが接続しにくい状態になります。

### 再現方法

1. GUI の [配信...] からソースが http、ストリームURLが `http://localhost:8080/` のチャンネルを作成して、そのチャンネルを [切断] します。
2. ソースが HTTP Push Source、ストリームURLが `http://localhost:8080/` のチャンネルを作成します。
3. 接続一覧に「NSPlayer (PeerCastStation/2.3.8.0)」と表示されてループバック接続が起こっていることがわかります。

![image](https://user-images.githubusercontent.com/1680210/29093415-c1b24fbc-7cc4-11e7-8321-f48533aa1345.png)
![image](https://user-images.githubusercontent.com/1680210/29093417-c48fd3a8-7cc4-11e7-8407-358eaa6f3080.png)

### 原因？

チャンネルが停止しても SourceStreamBase::eventTask のタスクチェインが動きつづけているようです。とりあえず継続の先頭に IsStopped 判定を入れたら再接続が止まりましたが、CancellationToken を直接ひっかけたりしたほうがよいかも…。

    protected Task Queue(Action action)
    {
      eventTask = eventTask.ContinueWith(prev => {
        if (prev.IsFaulted || IsStopped) return;
        action.Invoke();
      });
      return eventTask;
    }

### 動作環境
* OSバージョン: Windows7 と Linux
* .NET Frameworkバージョン:  .NET のバージョンの調べかたがわかりません…。mono は 4.6.2 です。
* PeerCastStationバージョン: 2.3.8

**Comment by kumaryu** [comment]
b53f7ed194cc4c2824e40a2a051eaccf6958ccf9 でついでに直りました。
チャンネル止めたあとも再接続のところに入ってぐるぐる動いちゃってたので、チャンネル止めたらそれ以降の再接続などができないようにしました。
