### ISSUE TITLE
開発版2.3.9でペカレコのダウンロード機能を使うと上流のコネクションが瞬断される

### ISSUE THREAD

**Issue by aki1-asr** [kumaryu/peercaststation#331]
### 問題と期待される動作
開発版2.3.9でペカレコのダウンロード機能を使用した際、不定期に上流のコネクションが瞬断されてしまう。
(ペカレコ <-> ペカステの接続ではなく、視聴しているchのPCP Sourceが切れる)
尚、切断が発生した場合同一上流に即再接続するため、再接続ボタンの挙動とは異なる模様。
この際プレイヤー側がrtmp接続の場合(mpv等)は継続して視聴可能だが、http接続系のものは瞬断後に一度切断されてしまうため、ダウロードやPCRPlayer等は一度停止してしまう。
本現象発生時のログはこちら。

[test2.log](https://github.com/kumaryu/peercaststation/files/1463891/test2.log)

### 再現方法
ペカステ2.3.9に対してペカレコで何かしらのchのダウンロードを行う。
(ペカレコの接続のみで瞬断現象は発生)
早ければ数十秒、遅くとも1時間以内にはほぼ確実に発生する。
尚、まっさらなOSに新規でペカステをインストールしたものを2セット用意し、ローカルのみで `OBS -> PCST(Tracker) -> PCST(直下) -> ペカレコ` というような疑似リレー環境を用意して検証した所こちらでも再現したため、環境による現象ではないと思われる。
(上記の場合、Trackerと直下の接続が切れる)
また、配信者側(Tracker)は2.2.0や2.2.1等でも本現象は同様に発生する。

### 動作環境
* OSバージョン: Windows10 Pro, Windows 8.1 Enterprise, Windows Server 2012 R2(検証用)
* .NET Frameworkバージョン: 4.7.1
* PeerCastStationバージョン: 2.3.9
* プレイヤー: PeCaRecorder 0.87, mpv 0.24.0

**Comment by aki1-asr** [comment]
補足忘れたので追記。
ログ中のIPですけど下記の通りです。
* 192.168.15.105: PCST Tracker
* 192.168.15.107: PCST 直下 / ペカレコ

**Comment by kumaryu** [comment]
#336 の方にも書きましたが、手元でなかなか再現させられてないので、思い当たるところを適当にいじって直ることを期待することにしました。
↓のアドレスにちょっといじってみたバージョンが上がってるのでできたら試してもらえないでしょうか。
https://ci.appveyor.com/project/kumaryu/peercaststation/build/artifacts

**Comment by aki1-asr** [comment]
ちょっと時間ができたので各バージョンでそれぞれ試してみました。
※ ビットレート2160kbpsのFLVでテスト

* 2.5.0: 1時間経過しても切断現象発生せず
* 2.3.9.167: 数十秒で切断現象確認
https://github.com/kumaryu/peercaststation/commit/8aa5e0716da87475c8ab2b08e8088106f45365c3
Sinkイベント発行順番修正の直前のコミットのやつ
* 2.3.9: 数十秒で切断現象確認
* 2.3.8.75: 数十秒で切断現象確認
https://github.com/kumaryu/peercaststation/commit/a59c5b6f9cc806bd20f2e82f5198bf92aaa7775c
* 2.3.8.74: 1時間経過しても切断現象発生せず
https://github.com/kumaryu/peercaststation/commit/6a46f7f8f17673e4d650e463089be274cfdd48b1

上記のような結果になったので、 https://github.com/kumaryu/peercaststation/commit/e9ea4b8c1d5a025810b5bd148de0d541b69b3dba のコミットで改善されたと判断してよいかと思います。
ありがとうございました。

**Comment by kumaryu** [comment]
詳細な調査ありがとうございます！
やっぱここが原因だったか。
直ったっぽいので閉じときます。
