### ISSUE TITLE
Access-Control-Allow-Originを有効にして欲しい

### ISSUE THREAD

**Issue by odangosan** [kumaryu/peercaststation#344]
### 問題と期待される動作
外部サーバーを用いてブラウザ上でflv.jsを使用して配信を再生・視聴するために、
Access-Control-Allow-Originを有効にして欲しい

> CORS Configuration

>Anytime you want to play an FLV stream from another Origin, the server must response with a CORS header:
Access-Control-Allow-Origin: <your-origin> | *

>For example, if an html on your site http://flvplayback.com want's to play an FLV from another Origin like http://cdn.flvplayback.com, the video server must response with the following CORS header:
Access-Control-Allow-Origin: http://flvplayback.com

>Or a wildcard value * to allow any request origin:
Access-Control-Allow-Origin: *

参考リンク
[https://github.com/Bilibili/flv.js/blob/master/docs/cors.md](https://github.com/Bilibili/flv.js/blob/master/docs/cors.md)

**Comment by kumaryu** [comment]
これって動画再生だけで良いでしょうか？
動画再生だけなら簡単に許可しちゃって良さそうなんですが、JSON-RPC APIは意図的にクロスオリジンで叩かれるのを弾いてるんで、APIも必要ならそっちは別に検討します。

**Comment by odangosan** [comment]
JSON-RPC APIはhttpクライアント経由でも呼び出せるので動画再生だけでも助かります。
ただ、[HTTP 要求のフォーマット](https://github.com/kumaryu/peercaststation/wiki/JSON-RPC-API-%E3%83%A1%E3%83%A2#http-%E8%A6%81%E6%B1%82%E3%81%AE%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)のサンプルを動かした時にエラーが出てしまいました。
環境依存なのか不明なので、APIの呼び出し順番などをライフサイクルのサンプル形式か何かで見られるようになるとありがたいです。
```
λ curl -H "X-Requested-With: XMLHttpRequest" -H "Content-Type: application/json" -X POST -d '{
"jsonrpc": "2.0","id": 6412,"method":"getVersionInfo"}' http://localhost:7144/api/1
curl: (6) Could not resolve host: 2.0,id
curl: (3) [globbing] unmatched close brace/bracket at pos 27
{
  "jsonrpc": "2.0",
  "id": null,
  "error": {
    "code": -32700,
    "message": "ParseError"
  }
}
```

**Comment by kumaryu** [comment]
POSTでX-Requested-WithヘッダはXHRだと付加できないですけど大丈夫ですかね。
どっちにしろ外からJSON-RPC叩けるようにも考えます。

エラーはcurlの段階で変なの出てるので環境(シェル？)依存だと思います。うちのmsys2ではそのまま動いたんで。

    curl: (6) Could not resolve host: 2.0,id
    curl: (3) [globbing] unmatched close brace/bracket at pos 27

このあたりでcurlが既にエラー吐いてるんで、リクエストの文字列をcurlに渡すあたりがだめかも？`{}`ってシェルによってはエスケープしないとだめなやつありませんでしたっけ。

**Comment by odangosan** [comment]
```
curl -H "X-Requested-With: XMLHttpRequest" -H "Content-Type: application/json" -X POST -d "{"jsonrpc":\"2.0\","id":6412,"method":\"getVersionInfo\"}" http://localhost:7144/api/1
```
で行けました👍

> POSTでX-Requested-WithヘッダはXHRだと付加できないですけど大丈夫ですかね。

例えばですがフロントからAPI的に接続リクエストをサーバに投げて、
帰ってきたら再生のような形を想定しているのでそれでも大丈夫だと思います。

**Comment by kumaryu** [comment]
ビデオだけ直接再生したいってことですね。
それならとりあえずはそこだけクロスオリジンでのアクセス許可すればいいっすね。
近いうちに入れてみます。

**Comment by kumaryu** [comment]
34a0cb9eacc19430b40834e141f410be13c22351 で入れました。

**Comment by kumaryu** [comment]
間違ってCloseしたけどなんか問題あったら再Openしてください。
