### ISSUE TITLE
v2.5.0 待ち受けポートにアクセスできなくなる 

### ISSUE THREAD

**Issue by Gniang** [kumaryu/peercaststation#347]
### 問題と期待される動作
PecaStationを再起動するまで、待ち受けポートにアクセスしても接続できなくなる。

該当状態のときのnetstatで自PCの待ち受けポート：CLOSE_WAIT
【StackTraceが出ている部分のログ抜粋】（IP部分はXXで置き換え）
PCPOutputStream[XX.XX.XX.XX:64591]: 2018-05-04T22:15:55 ERROR - NullReferenceException オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 PeerCastStation.PCP.PCPSourceConnection.CreatePCPHOST()
   場所 PeerCastStation.PCP.PCPSourceConnection.BroadcastHostInfo()
   場所 PeerCastStation.Core.Channel.AddNode(Host host)
   場所 PeerCastStation.PCP.PCPOutputStream.OnPCPHost(Atom atom, CancellationToken cancel_token)
   場所 PeerCastStation.PCP.PCPOutputStream.<ProcessAtom>d__46.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<OnPCPBcst>d__57.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<ProcessAtom>d__46.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<ReadAndProcessAtom>d__42.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<DoProcess>d__43.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext()

### 再現方法
不明。視聴中に発生し具体的なタイミングなどは不明。
（リレー再接続時だったかどうかなど）

### 動作環境
* OSバージョン:Windows10 1803 x64
* .NET Frameworkバージョン: 4.7.0356
* PeerCastStationバージョン: zip 2.5.0
* プレイヤー: pcrplayer

**Comment by Gniang** [comment]
2.5.1ですがまた発生し、今度はデバッグファイルから
コード行位置がでてるようなので追記

PCPOutputStream[XXX.XXX.XXX.XXX:53955]: 2018-08-26T18:29:09 ERROR - NullReferenceException オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 PeerCastStation.PCP.PCPSourceConnection.CreatePCPHOST() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPSourceStream.cs:行 382
   場所 PeerCastStation.PCP.PCPSourceConnection.BroadcastHostInfo() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPSourceStream.cs:行 453
   場所 PeerCastStation.Core.Channel.AddNode(Host host) 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.Core\Channel.cs:行 552
   場所 PeerCastStation.PCP.PCPOutputStream.OnPCPHost(Atom atom, CancellationToken cancel_token) 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 864
   場所 PeerCastStation.PCP.PCPOutputStream.<ProcessAtom>d__46.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 638
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<OnPCPBcst>d__57.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 833
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<ProcessAtom>d__46.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 637
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<ReadAndProcessAtom>d__42.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 494
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.PCP.PCPOutputStream.<DoProcess>d__43.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.PCP\PCPOutputStream.cs:行 534
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.Core\OutputStreamBase.cs:行 154
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 PeerCastStation.Core.OutputStreamBase.<Start>d__54.MoveNext() 場所 C:\Users\kumaryu\OneDrive\Documents\peercaststation\PeerCastStation\PeerCastStation.Core\OutputStreamBase.cs:行 168
PCPOutputStream[XXX.XXX.XXX.XXX:59000]: 2018-08-26T18:34:40 ERROR - Content Skipped: serial 604655 expected but was 604660


再現方法
バッファ時のリレー再構築中?

動作環境
OSバージョン:Windows10 1803 x64
.NET Frameworkバージョン: 4.7.0356
PeerCastStationバージョン: zip 2.5.1
プレイヤー: pcrplayer

**Comment by kumaryu** [comment]
ありがとうございます。長らく直せてなくてすみません。
593dcb8243cf0b0efcfcf8b3de90027e6f0c79ac で直しました。
手元では擬似的に再現させたんで、ポートにアクセスできなくなるのがこれが原因かどうかまでは突き止められてないんですが、少なくとも同じエラーは出なくなると思いますし、リレー再構築中の安定度は増します。
次の開発版リリースには載せます。
