### ISSUE TITLE
Debian(buster)においてIPv6 Anyの待ち受けをIPv4と同一のポートで行えない

### ISSUE THREAD

**Issue by Philmist** [kumaryu/peercaststation#357]
### 問題と期待される動作
IPv4と同一のポートで待ち受けて欲しいが、ポートが使用されているとして拒否され設定されない。
なお、別ポートでは待ち受け可能。

### 再現方法
設定→追加→IPv6 Any+ポート7144(IPv4で使用しているポート)+追加→(追加されない)

その際のPeercastStationのログ:
```
PeerCast: 2018-06-11T18:52:22 ERROR - Listen failed: [::]:7144
PeerCast: 2018-06-11T18:52:22 ERROR - SocketException Address already in use
  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) [0x00043] in <fc308f916aec4e4283e0c1d4b761760a>:0 
  at System.Net.Sockets.TcpListener.Start (System.Int32 backlog) [0x00044] in <fc308f916aec4e4283e0c1d4b761760a>:0 
  at PeerCastStation.Core.OutputListener..ctor (PeerCastStation.Core.PeerCast peercast, PeerCastStation.Core.IConnectionHandler connection_handler, System.Net.IPEndPoint ip, PeerCastStation.Core.OutputStreamType local_accepts, PeerCastStation.Core.OutputStreamType global_accepts) [0x0009a] in <3237711e93c1401b9b84a62e079a46c9>:0 
  at PeerCastStation.Core.PeerCast.StartListen (System.Net.IPEndPoint ip, PeerCastStation.Core.OutputStreamType local_accepts, PeerCastStation.Core.OutputStreamType global_accepts) [0x0002e] in <3237711e93c1401b9b84a62e079a46c9>:0 
```

`sudo netstat -a -p -n | grep 7144`の結果:
```
tcp        0      0 192.168.0.100:7144      0.0.0.0:*               LISTEN      1601/mono-sgen      
tcp        0      0 192.168.0.100:7144      192.168.0.101:55983     ESTABLISHED 1601/mono-sgen      
tcp        0      0 192.168.0.100:7144      192.168.0.101:56460     ESTABLISHED 1601/mono-sgen      
tcp        0      0 192.168.0.100:7144      192.168.0.101:56463     ESTABLISHED 1601/mono-sgen      
tcp        0      0 192.168.0.100:7144      192.168.0.101:55981     ESTABLISHED 1601/mono-sgen      
tcp        0      0 192.168.0.100:7144      192.168.0.101:56440     TIME_WAIT   -                   
tcp        0      0 192.168.0.100:7144      192.168.0.101:56442     TIME_WAIT   - 
```

### 動作環境
* OSバージョン: Linux Debian buster(testing)
* .NET Frameworkバージョン: Mono 5.12.0.226
* PeerCastStationバージョン: PeercastStation 2.5.2.0 (zip版)
* プレイヤー: PCRPlayer (外部からWindows10で)

**Comment by kumaryu** [comment]
DualStack Socketみたいなのがあるのかなあ
IPv6のアドレスをAnyでなく待ち受けたり([::1]とか)、IPv4側をAnyじゃなくした場合にどうなるか試せますか？

**Comment by Philmist** [comment]
元々、何故かこんな( 
![image](https://user-images.githubusercontent.com/431640/41391542-3e8aac50-6fd6-11e8-91e5-1f55c38e1be9.png) )感じの設定だったんですよね。
で、LinuxはHTML UIしか無いので、設定追加はコンボボックスのIPv6 Anyしか選べないので、
[::1]とかの他のアドレスは恐らく設定ファイルを直に書き換えるしか設定できないように思います。

設定ファイル(~/.config/PeerCastStation/PeCasettings.xml)をいじればいいですかね？

**Comment by Philmist** [comment]
あー…試しにプロセスkillして設定ファイルを直に書き換えても、PeCaSt起動すると元に戻っちゃいますね。
たぶんこっちの環境で悪さしてるんだと思いますが……。

**Comment by Philmist** [comment]
＞IPv6のアドレスをAnyでなく待ち受けたり([::1]とか)、IPv4側をAnyじゃなくした場合にどうなるか試せますか？

これやろうとしたんですが、killallしてmonoのプロセス全部落として、設定ファイルいじって再始動かけても設定ファイル自体が元に戻ってしまいますね。

**Comment by Philmist** [comment]
https://serverfault.com/questions/21657/semantics-of-and-0-0-0-0-in-dual-stack-oses にある情報を元に設定してみても同様の症状が起こりますね。

**Comment by kumaryu** [comment]
IPv6 mapped IPv4アドレスも受け付けちゃうのか……
IPV6_V6ONLY のオプション入れろって書いてあるんで調べてみます。

**Comment by kumaryu** [comment]
#360 で対応してみました。
手元でWSLのUbuntuでは標準でデュアルスタックにはならんかったので再現できてないんで、試してもらえると助かります。
https://ci.appveyor.com/project/kumaryu/peercaststation/build/2.5.2.226/artifacts

**Comment by Philmist** [comment]
試してみました。
解放確認までちょっと時間がかかった(たぶんおま環)以外は、
同じポートで待ち受けできました。
![image](https://user-images.githubusercontent.com/431640/41810697-b97047e0-773d-11e8-97aa-2af5bfa28f4f.png)

一応chもYPv6に載りましたが、あれを自分で見るのは結構手間ですネ。

**Comment by kumaryu** [comment]
thx!
マージしときました。
