### ISSUE TITLE
PeerCastStationのプロセスが残る

### ISSUE THREAD

**Issue by f0n4c** [kumaryu/peercaststation#361]
### 問題と期待される動作
PeCaRecorder_v077で連動して終了させる設定だと、上手く終了出来ずにプロセスに残る
taskkillも効かないのでペカが見たいなら再起動するしか無い
### 再現方法
PeCaRecorderで連動して終了させる設定にして起動終了ループで再現可能
### 動作環境
* OSバージョン: (OSのバージョンを書いてください: Windows 7 x64
* .NET Frameworkバージョン: (.NET Framework 4.7.2)
* PeerCastStationバージョン: (2.2.1と2.5.3のzipで発症した)
* プレイヤー: (PCRPlayer)

**Comment by kumaryu** [comment]
さすがにkillできない状態はおかしいですね。
PeCaRecorderはPeerCastのプロセスをkillして終了させてるので、PeCaRecorder関係なくkillできなくなってるというのがそもそもの現象のように思えます。
アプリというより.NET FrameworkレベルまたはOSレベルでなんかおかしくなってる気がします。

なんかセキュリティソフトとか使ってますか？
使ってればOFFにしてみて再現するか試してもらえますでしょうか。

**Comment by f0n4c** [comment]
avira無効にしても変わらなかったので
.net4.7.2を削除してから4.5.2にしたら今のところはこの現象は起きてません
たぶん私の環境の問題だったんでしょうね。お手数かけました

**Comment by kumaryu** [comment]
.NET Frameworkの調子が悪くなってたんですかねえ。
再インストールで直ってる雰囲気もあるのでもしかしたら4.7.2をもう一回入れたら上手くいくかもしれないですね。
まあ4.5.2でもPeerCastStation的にはなんら問題ないですけど。

他の人からも似たような報告は今のところ無いのでとりあえず解決ということで閉じておきます。
また再発などあれば再オープンなり新しくIssue立てるなりしてください。
