### ISSUE TITLE
UPnPでは配信を視聴できない

### ISSUE THREAD

**Issue by darklie** [kumaryu/peercaststation#369]
### 問題と期待される動作
どの配信を見ようとしても何故か視聴できない
配信が終わった扱いになってしまう
### 再現方法
配信のURLをごく普通にプレイヤーの開くURLにコピペして再生する
### 動作環境
* OS:Windows10 Pro(64bit)
* .NET Frameworkバージョン: 多分4.7.2
* PeerCastStationバージョン: PeerCastStationはバージョン2.5.3のサービス版
* ルーター:BUFFALO製WSR-2533DHP2
* プロバイダー:BBIQ IPv4環境
* プレイヤー: どのプレイヤーでも発生します

その時のログがこのような感じになっています

> PCPSourceStream[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Initialized: Channel cdd75668ab399a30c8547d5bb370500e, Source pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e
> HTTPOutputStream[127.0.0.1:63671]: 2018-11-20T16:39:26 DEBUG - Initialized: Channel cdd75668ab399a30c8547d5bb370500e, Remote 127.0.0.1:63671, Request GET http://localhost:7144/stream/CDD75668AB399A30C8547D5BB370500E?tip=116.82.29.121:7144
> ConnectionHandler: 2018-11-20T16:39:26 DEBUG - Output stream started 0
> HTTPOutputStream[127.0.0.1:63671]: 2018-11-20T16:39:26 DEBUG - Starting
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Connected: pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Started
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Sending Relay request: /channel/cdd75668ab399a30c8547d5bb370500e
> OutputListener: 2018-11-20T16:39:26 INFO - Client connected 192.168.11.1:63672
> ConnectionHandler: 2018-11-20T16:39:26 DEBUG - Output thread started
> PCPOutputStream[192.168.11.1:63672]: 2018-11-20T16:39:26 DEBUG - Initialized: Channel cdd75668ab399a30c8547d5bb370500e, Remote 192.168.11.1:63672, Request http://localhost/channel/cdd75668ab399a30c8547d5bb370500e 0 (1 PeerCastStation/2.5.3.0)
> ConnectionHandler: 2018-11-20T16:39:26 DEBUG - Output stream started 0
> PCPOutputStream[192.168.11.1:63672]: 2018-11-20T16:39:26 DEBUG - Starting
> PCPOutputStream[192.168.11.1:63672]: 2018-11-20T16:39:26 DEBUG - SendingRelayResponse: HTTP/1.0 404 Not Found.
> Server: PeerCastStation/2.5.3.0
> 
> 
> PCPOutputStream[192.168.11.1:63672]: 2018-11-20T16:39:26 DEBUG - Finished
> ConnectionHandler: 2018-11-20T16:39:26 DEBUG - Closing client connection
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Relay response: 404
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 INFO - Server responses 404 to GET /cdd75668-ab39-9a30-c854-7d5bb370500e
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Disconnected
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - Finished
> PCPSourceConnection[pcp://116.82.29.121:7144/cdd75668-ab39-9a30-c854-7d5bb370500e]: 2018-11-20T16:39:26 DEBUG - closed
> HTTPOutputStream[127.0.0.1:63671]: 2018-11-20T16:39:26 DEBUG - Header: HTTP/1.0 503 ServiceUnavailable

> PeerCast: 2018-11-20T16:50:20 DEBUG - Requesting channel d12cf43c0c8ae6b5b2d8ad53446b162e from pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e
> PCPSourceStream[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Initialized: Channel d12cf43c0c8ae6b5b2d8ad53446b162e, Source pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e
> HTTPOutputStream[127.0.0.1:64612]: 2018-11-20T16:50:20 DEBUG - Initialized: Channel d12cf43c0c8ae6b5b2d8ad53446b162e, Remote 127.0.0.1:64612, Request GET http://localhost:7144/stream/D12CF43C0C8AE6B5B2D8AD53446B162E?tip=153.210.197.14:7144
> ConnectionHandler: 2018-11-20T16:50:20 DEBUG - Output stream started 32
> HTTPOutputStream[127.0.0.1:64612]: 2018-11-20T16:50:20 DEBUG - Starting
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Connected: pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Started
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Sending Relay request: /channel/d12cf43c0c8ae6b5b2d8ad53446b162e
> OutputListener: 2018-11-20T16:50:20 INFO - Client connected 192.168.11.1:64648
> ConnectionHandler: 2018-11-20T16:50:20 DEBUG - Output thread started
> PCPOutputStream[192.168.11.1:64648]: 2018-11-20T16:50:20 DEBUG - Initialized: Channel d12cf43c0c8ae6b5b2d8ad53446b162e, Remote 192.168.11.1:64648, Request http://localhost/channel/d12cf43c0c8ae6b5b2d8ad53446b162e 0 (1 PeerCastStation/2.5.3.0)
> ConnectionHandler: 2018-11-20T16:50:20 DEBUG - Output stream started 0
> PCPOutputStream[192.168.11.1:64648]: 2018-11-20T16:50:20 DEBUG - Starting
> PCPOutputStream[192.168.11.1:64648]: 2018-11-20T16:50:20 DEBUG - SendingRelayResponse: HTTP/1.0 404 Not Found.
> Server: PeerCastStation/2.5.3.0
> 
> 
> PCPOutputStream[192.168.11.1:64648]: 2018-11-20T16:50:20 DEBUG - Finished
> ConnectionHandler: 2018-11-20T16:50:20 DEBUG - Closing client connection
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Relay response: 404
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 INFO - Server responses 404 to GET /d12cf43c-0c8a-e6b5-b2d8-ad53446b162e
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Disconnected
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - Finished
> PCPSourceConnection[pcp://153.210.197.14:7144/d12cf43c-0c8a-e6b5-b2d8-ad53446b162e]: 2018-11-20T16:50:20 DEBUG - closed
> HTTPOutputStream[127.0.0.1:64612]: 2018-11-20T16:50:20 DEBUG - Header: HTTP/1.0 503 ServiceUnavailable
> 

ちなみにリレー画面はこのような表示になっています

![image](https://user-images.githubusercontent.com/12250058/48758893-dbda1000-ece4-11e8-85bb-da4d59dd3f34.png)

なぜこのような現象が起きているのかご教授いただけると幸いです

**Comment by kumaryu** [comment]
ログ見る限り、なぜか自分自身にリレー接続しに行ってるように見えますねえ。
どうなったらそういう現象になるのか調べてみます。

ちなみに安定版ではどうなるか試してみてもらえるでしょうか？

**Comment by darklie** [comment]
安定版でも同様でした
そして不思議なことに気がついたのですが、UPnPをONにすると何故かその現象が起き、しかも情報画面での「リレー可能アドレス」が表示されず、逆にUPnPをOFFにするとその現象が起きずにちゃんと接続でき、しかもポート開放チェックや情報画面ではポートが空いていないはずの表示になっているのになぜかリレー画面ではちゃんとリレーされているかのように表示される……という本当に分けのわからないことになっています
ちなみにちゃんと再生されたときのログはこのような形になっています

> OutputListener: 2018-11-21T00:25:33 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:49705
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49705] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49704] DEBUG  - Initialized: Remote 127.0.0.1:49704
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49704] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49703] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49703] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49703] DEBUG  - Output thread finished
> APIHostOutputStream: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49705] DEBUG  - Initialized: Remote 127.0.0.1:49705
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49705] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49704] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49705] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49704] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49704] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49704] DEBUG  - Output thread finished
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49705] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49705] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49705] DEBUG  - Output thread finished
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:63797] INFO  - IOException 受信エラーが発生しました
>    場所 PeerCastStation.Core.StreamConnection.RethrowExceptions()
>    場所 PeerCastStation.Core.OutputStreamBase.DoProcess()
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:63797] INFO  - EndOfStreamException ストリームの末尾を越えて読み取ろうとしました。
> 
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:63797] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:63797] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:63797] DEBUG  - Output thread finished
> OutputListener: 2018-11-21T00:25:33 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:49706
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49706] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49706] DEBUG  - Initialized: Remote 127.0.0.1:49706
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49706] DEBUG  - Output stream started
> OutputListener: 2018-11-21T00:25:33 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:49707
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49706] DEBUG  - Started
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49707] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49707] DEBUG  - Initialized: Remote 127.0.0.1:49707
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49707] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49707] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49706] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49706] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49706] DEBUG  - Output thread finished
> APIHostOutputStream: 2018-11-21T00:25:33 [APIHostOutputStream:127.0.0.1:49707] DEBUG  - Finished
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49707] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49707] DEBUG  - Output thread finished
> OutputListener: 2018-11-21T00:25:33 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:49708
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49708] DEBUG  - Output thread started
> HTTPOutputStream: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49708] DEBUG  - Initialized: Channel f56d778a28f6ed6a673734770857bf60, Remote 127.0.0.1:49708, Request GET http://127.0.0.1:7144/stream/F56D778A28F6ED6A673734770857BF60
> OutputListener: 2018-11-21T00:25:33 [OutputThread:127.0.0.1:49708] DEBUG  - Output stream started
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:49708] DEBUG  - Starting
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:49708] DEBUG  - ContentType: FLV
> HTTPOutputStream: 2018-11-21T00:25:33 [HTTPOutputStream:127.0.0.1:49708] DEBUG  - Header: HTTP/1.0 200 OK
> Content-Type: video/x-flv

UPnP関係やらリレーと開放確認画面でのポートの状況が食い違うということで #366 や #308 辺りとも関連していそうな雰囲気もひしひししますがどうなんでしょう……？

**Comment by darklie** [comment]
追記:UPnP切ったあともリレー状況が◎が続くのは流石に5分ほどでしばらくしたら×になりました
ただUPnPを入れると視聴できなくなるのに入れないと逆に視聴できる状況は相変わらずです

**Comment by kumaryu** [comment]
UPnPを有効にしてるとそれ関係のログが出ると思いますが、その行を探してコピペしてもらえますか？
WANConnectionServiceで始まる行です。

何を思ったか内から外に行くパケットも指定のポート/アドレスに転送しちゃう挙動してんじゃないかという気がする……

**Comment by darklie** [comment]
UPnP周辺自体はログぱっと見る限り変な動作指定なさそうなのがまた不思議なんですよね……
いくつか抜き出すとこんな感じです

> WANConnectionService: 2018-11-21T01:19:11 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress to http://192.168.11.1:45525/ctl/IPConn
> WANConnectionService: 2018-11-21T01:19:11 [] INFO  - UPnP Action GetExternalIPAddress Success
> WANConnectionService: 2018-11-21T01:19:11 [] DEBUG  - Param NewExternalIPAddress:210.203.213.134
> OutputListener: 2018-11-21T01:19:12 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62301
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62301] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62301] DEBUG  - Initialized: Remote 127.0.0.1:62301
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62301] DEBUG  - Output stream started
> OutputListener: 2018-11-21T01:19:12 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62302
> APIHostOutputStream: 2018-11-21T01:19:12 [APIHostOutputStream:127.0.0.1:62301] DEBUG  - Started
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62302] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62302] DEBUG  - Initialized: Remote 127.0.0.1:62302
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62302] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T01:19:12 [APIHostOutputStream:127.0.0.1:62302] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T01:19:12 [APIHostOutputStream:127.0.0.1:62301] DEBUG  - Finished
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62301] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62301] DEBUG  - Output thread finished
> APIHostOutputStream: 2018-11-21T01:19:12 [APIHostOutputStream:127.0.0.1:62302] DEBUG  - Finished
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62302] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:19:12 [OutputThread:127.0.0.1:62302] DEBUG  - Output thread finished
> OutputListener: 2018-11-21T01:19:13 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62303
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62303] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62303] DEBUG  - Initialized: Remote 127.0.0.1:62303
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62303] DEBUG  - Output stream started
> OutputListener: 2018-11-21T01:19:13 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62304
> APIHostOutputStream: 2018-11-21T01:19:13 [APIHostOutputStream:127.0.0.1:62303] DEBUG  - Started
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62304] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62304] DEBUG  - Initialized: Remote 127.0.0.1:62304
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62304] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T01:19:13 [APIHostOutputStream:127.0.0.1:62304] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T01:19:13 [APIHostOutputStream:127.0.0.1:62303] DEBUG  - Finished
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62303] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62303] DEBUG  - Output thread finished
> WANConnectionService: 2018-11-21T01:19:13 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> APIHostOutputStream: 2018-11-21T01:19:13 [APIHostOutputStream:127.0.0.1:62304] DEBUG  - Finished
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62304] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:19:13 [OutputThread:127.0.0.1:62304] DEBUG  - Output thread finished
> WANConnectionService: 2018-11-21T01:19:13 [] INFO  - UPnP Action AddPortMapping Success
> OutputListener: 2018-11-21T01:19:13 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 150.95.9.126:45938
> OutputListener: 2018-11-21T01:19:13 [OutputThread:150.95.9.126:45938] DEBUG  - Output thread started
> WANConnectionService: 2018-11-21T01:19:13 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> WANConnectionService: 2018-11-21T01:19:13 [] INFO  - UPnP Action AddPortMapping Success


> WANConnectionService: 2018-11-21T01:20:13 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> WANConnectionService: 2018-11-21T01:20:13 [] INFO  - UPnP Action AddPortMapping Success
> OutputListener: 2018-11-21T01:20:13 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62513
> WANConnectionService: 2018-11-21T01:20:13 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62513] DEBUG  - Output thread started
> OutputListener: 2018-11-21T01:20:13 [OutputListenerThread:0.0.0.0:7144] INFO  - Client connected 127.0.0.1:62514
> APIHostOutputStream: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62513] DEBUG  - Initialized: Remote 127.0.0.1:62513
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62513] DEBUG  - Output stream started
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62514] DEBUG  - Output thread started
> APIHostOutputStream: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62514] DEBUG  - Initialized: Remote 127.0.0.1:62514
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62514] DEBUG  - Output stream started
> APIHostOutputStream: 2018-11-21T01:20:13 [APIHostOutputStream:127.0.0.1:62513] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T01:20:13 [APIHostOutputStream:127.0.0.1:62514] DEBUG  - Started
> APIHostOutputStream: 2018-11-21T01:20:13 [APIHostOutputStream:127.0.0.1:62514] DEBUG  - Finished
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62514] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62514] DEBUG  - Output thread finished
> APIHostOutputStream: 2018-11-21T01:20:13 [APIHostOutputStream:127.0.0.1:62513] DEBUG  - Finished
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62513] DEBUG  - Closing client connection
> OutputListener: 2018-11-21T01:20:13 [OutputThread:127.0.0.1:62513] DEBUG  - Output thread finished
> WANConnectionService: 2018-11-21T01:20:13 [] INFO  - UPnP Action AddPortMapping Success


> WANConnectionService: 2018-11-21T01:21:18 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> WANConnectionService: 2018-11-21T01:21:18 [] INFO  - UPnP Action AddPortMapping Success
> WANConnectionService: 2018-11-21T01:21:18 [] DEBUG  - Sending UPnP Action urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping to http://192.168.11.1:45525/ctl/IPConn
> WANConnectionService: 2018-11-21T01:21:18 [] INFO  - UPnP Action AddPortMapping Success

**Comment by kumaryu** [comment]
UPnPの実行自体は普通ぽいな……
ポートを7144以外にして他の配信視聴できるか試してもらえるでしょうか？
できそうな気もする

**Comment by darklie** [comment]
ポートを7145にしてみたらたしかに安定して視聴できますね……
ログもおそらく普通な状態かと思われます

> OutputListener: 2018-11-21T13:54:06 [OutputListenerThread:0.0.0.0:7145] INFO  - Client connected 127.0.0.1:57309
> OutputListener: 2018-11-21T13:54:06 [OutputThread:127.0.0.1:57309] DEBUG  - Output thread started
> PeerCast: 2018-11-21T13:54:06 [OutputThread:127.0.0.1:57309] DEBUG  - Requesting channel 260a18ea750e9856a6f07f3a11b4488f from pcp://126.124.234.83:7144/260a18ea-750e-9856-a6f0-7f3a11b4488f
> PCPSourceStream: 2018-11-21T13:54:06 [OutputThread:127.0.0.1:57309] DEBUG  - Initialized: Channel 260a18ea750e9856a6f07f3a11b4488f, Source pcp://126.124.234.83:7144/260a18ea-750e-9856-a6f0-7f3a11b4488f
> HTTPOutputStream: 2018-11-21T13:54:06 [OutputThread:127.0.0.1:57309] DEBUG  - Initialized: Channel 260a18ea750e9856a6f07f3a11b4488f, Remote 127.0.0.1:57309, Request GET http://localhost:7145/stream/260A18EA750E9856A6F07F3A11B4488F?tip=126.124.234.83:7144
> OutputListener: 2018-11-21T13:54:06 [OutputThread:127.0.0.1:57309] DEBUG  - Output stream started
> HTTPOutputStream: 2018-11-21T13:54:06 [HTTPOutputStream:127.0.0.1:57309] DEBUG  - Starting
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Started
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Connected: 126.124.234.83:7144
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Sending Relay request: /channel/260a18ea750e9856a6f07f3a11b4488f
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Relay response: 200
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Handshake Started
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Handshake Finished: 210.203.213.134
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Broadcasting host info
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Broadcasting host info
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Broadcasting host info
> PCPSourceConnection: 2018-11-21T13:54:06 [] DEBUG  - Broadcasting host info
> HTTPOutputStream: 2018-11-21T13:54:06 [HTTPOutputStream:127.0.0.1:57309] DEBUG  - ContentType: FLV
> HTTPOutputStream: 2018-11-21T13:54:07 [HTTPOutputStream:127.0.0.1:57309] DEBUG  - Header: HTTP/1.0 200 OK
> Content-Type: video/x-flv

**Comment by kumaryu** [comment]
やっぱり内からのパケットも開けたポートに転送されてるみたいですね。
7144のポートを開けると外から7144に接続に来たやつが自分の7144ポートに転送されるんですが、
自分が他所の7144に接続しに行った時も自分の7144ポートに転送されちゃってるようです。
たぶんUPnPで7144ポート開けた状態で http://www.google.com:7144/html/index.html とかにアクセスするとPeerCastStationのHTML UIが表示されちゃうと思います。
7145を開けた場合は、接続先がだいたい7144なので転送設定はされてないので上手くいくんでしょう。ただこの場合も、接続先がたまたま7145ポートだった場合にはやっぱり上手くつながらないのでこの状態で運用するのはおすすめできません。

ルータのUPnPの実装バグなんでこっちで対処できなさそうな気もするんですが、PeerCastStationが現状無駄にUDPのポートも開けてるせいかも？ってのが気になるので、そこ外したのを作ってみるんで試してもらえると助かります。
しかし2018年にもなってUPnPをまともに実装できてないルーターが発売されてるとかびっくりですね。

**Comment by kumaryu** [comment]
UPnPでUDPのポート開けを外したやつを作ってみました。こいつを試してもらえるでしょうか。
https://ci.appveyor.com/project/kumaryu/peercaststation/builds/20478639/artifacts
あんまり望みはないですが、もし上手くいったらこの対処を入れとこうと思います。
UDPのポート開けは今のところ使ってないので。

**Comment by darklie** [comment]
UDPのポート開けを外したものも試してみましたがやはり上手くいきませんでした。
そしてルーターのバグらしきものはまさにkumaryuさんの想像通りでPeerCastStatonでポート7144を開ければポート7144のあらゆるホストを、ポート7145を開ければポート7145のあらゆるホストをアドレス欄に入れればPeerCastStationのサイトが見れる素敵な状態になっていました
このルーターの不具合を解消するためにルーターのサポートに連絡を入れ、当面はUPnPを使わずに手動で7144を開けてPeerCastStationを使っていこうかと思います
ありがとうございました

**Comment by kumaryu** [comment]
いろいろ試してもらってありがとうございます！
ルーター側が直るといいね！
とりあえずPeerCastStation側で出来ることはなさそうなので閉じときます。
