### ISSUE TITLE
帯域の自動測定時、測定結果が速すぎる場合測定値がマイナスになってしまう

### ISSUE THREAD

**Issue by aki1-asr** [kumaryu/peercaststation#376]
### 問題と期待される動作

2.5.4.0で実装された高精度の自動帯域測定において、測定結果が速すぎる(250～300Mbps程度)場合測定値がマイナスとなり、設定値には0が入力されてしまう。
厳密な境界は確認できないが、212483kbpsまで正常に表示されることは確認済み。
( `DataSize*8` の所がintなので、262144kbps以上かも?)

![speedtest](https://user-images.githubusercontent.com/28526152/52687037-8c2d7c80-2f93-11e9-94a1-7485a8e9b6a6.png)

### 再現方法

ナイスな品質の良い回線で測定する。

### 動作環境

* Windows 8 Enterprise 64bit, Windows 10 Pro 64bit
* .NET Frameworkバージョン: 4.7.2
* 開発ZIP版 2.5.4.0 
* プレイヤー: mpv 0.29.0-28-ga5b0d59084

**Comment by kumaryu** [comment]
お恥ずかしいバグを……
0c6970d744174f402583d81ccf78733234f6568a で修正しました。
