### ISSUE TITLE
帯域の自動測定を途中でキャンセルすると落ちる

### ISSUE THREAD

**Issue by aki1-asr** [kumaryu/peercaststation#377]
### 問題と期待される動作

2.6.0(2.5.4)以降の帯域自動測定を途中でキャンセルした際、下記の現象が発生する。

1. キャンセルすると測定ウィンドは閉じるが、バックグラウンドでは10秒経過するまで通信し続けている
2. 10秒通信し続けた後 `PeerCastStation は動作を停止しました` でペカステが落ちる

尚、デバッグログを有効にしても帯域測定では特に追記が無かったので、ログ添付は無しです。

### 再現方法

帯域測定ウィンドウでキャンセルをクリックする。
IPv4, IPv6両方で再現性100%。

### 動作環境

* Windows 8 Enterprise 64bit
* .NET Frameworkバージョン: 4.7.2
* AppVeyor ZIP版 2.6.0.279
* プレイヤー: -

**Comment by kumaryu** [comment]
9173eb3abe994d5ed825300ece3ad923ab46c91c で修正しました。
あとキャンセルしたあとも計測続いちゃってるのもすぐ終わるようにしました。
