### ISSUE TITLE
ポート開放確認機能でポートが閉じていることが判定できない

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#393]
### 問題と期待される動作

ポートが開いておらず、外部からのアクセスに応答しない場合、ポート開放確認を行うと、(ローカルでの5秒タイムアウトが発動して)確認処理自体が失敗します。ポート開放確認サーバーが、1~2分程度応答を返さないことがあるようです。

![image](https://user-images.githubusercontent.com/1680210/53699145-9f13ce00-3e28-11e9-8baf-12b09817ba97.png)

HTML UI の場合ですと、該当ポートの「開放状態」に「未開放」と表示されて、「ポート開放確認」ボタンの右のラベルに「開放されてません」と表示されて欲しいです。

### 再現方法

ポートが開いておらず、UPnPも働かないネットワーク環境で HTML UI の設定ページを開く。

### 動作環境
* PeerCastStationバージョン: 2.7.0

**Comment by kumaryu** [comment]
サーバー側で指定のポートに4秒で接続できなかったら未開放扱いにして返すようにしました。
