### ISSUE TITLE
[WPF GUI] IPv6の帯域自動設定で実際にはIPv4が使われる

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#394]
### 問題

GUI から IPv6 の帯域測定をすると、IPv4 の帯域測定サーバー(api.pecastation.org)が使われます。

[BandwidthCheckDialog.xaml.cs にある BandwidthCheckDialog クラス](https://github.com/kumaryu/peercaststation/blob/v2.7.0/PeerCastStation/PeerCastStation.WPF/CoreSettings/BandwidthCheckDialog.xaml.cs#L21)の OnInitialized メソッドで NetworkType プロパティの値によって IPv4 の帯域測定サーバーが使われるか IPv6 のサーバーが使われるかが振り分けられるのですが、同クラスのコンストラクタで NetworkType がセットされる前に InitializeComponent メソッドが呼ばれており、その結果 OnInitialized が呼ばれるため、OnInitialized が実行されるときは常に NetworkType がデフォルト値である NetworkType.IPv4 になっていることが原因かと思います。

ただし、代入を InitializeComponent の呼び出しの前に持ってくると私の環境（IPv6は使えません）では以下のエラーで PeerCastStation が落ちました。

```
System.Net.Sockets.SocketException (0x80004005): 要求した名前は有効ですが、要求された種類のデータは見つかりませんでした。
```

### 再現方法

GUI の設定ウィンドウを開き、「全般」タブで２つ目の「自動測定」ボタンを押す。

### 動作環境
* OSバージョン: Windows 7
* PeerCastStationバージョン: 2.7.0

**Comment by kumaryu** [comment]
直ってると思われるので閉じときます
