### ISSUE TITLE
[GUI] 接続待ち受けタブで追加ボタンを押すと2つポートが追加されることがある

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#397]
### 問題と期待される動作

接続待ち受けタブで全てのポートを削除したあと、追加ボタンを押すと 7144 と 7145 の2つのポートが追加されます。

最初のポートを追加する場合でも、1つだけポートが追加されて欲しいです。

![image](https://user-images.githubusercontent.com/1680210/53785354-8e17a980-3f5b-11e9-85cc-f072d1431b40.png)
![image](https://user-images.githubusercontent.com/1680210/53785372-9a9c0200-3f5b-11e9-897f-2bcf4460ca93.png)

### 再現方法

設定ウィンドウを開き、詳細設定ラジオボタンを押し、表示された接続待ち受けタブに切り替え、全てのポートを削除したあと、追加ボタンを押す。

### 動作環境
* OSバージョン: Windows 7
* PeerCastStationバージョン: 2.7.0

**Comment by kumaryu** [comment]
直ってるので閉じときます。
