### ISSUE TITLE
[GUI] 数値フィールドに下限値未満の値を入力することができる

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#399]
### 問題と期待される動作

通常、GUIの数値入力フィールドに下限値未満の値を入れると下限値に直されるのですが、すでにフィールドが下限値であるときに下限値未満の値を入力しても直されません。

![image](https://user-images.githubusercontent.com/1680210/53786158-2020b180-3f5e-11e9-9e91-754a80a40403.png)

### 再現方法

設定ウィンドウを開き、「最大上り帯域」「合計(IPv4)」の部分の  0 を入れてエンターキーを押す、同フィールドに -100 を入れてエンターキーを押す。0 になることが期待されるが、-100 のままになる。

### 動作環境
* OSバージョン: Windows 7
* PeerCastStationバージョン: 2.7.0

**Comment by kumaryu** [comment]
直ってるので閉じときます。
