### ISSUE TITLE
[HTML UI] IPv6 Any アドレスなポートの「認証付きURL」がおかしい

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#402]
### 問題と期待される動作

HTML UI 設定ページのポート一覧に IPv6 Any がある場合、認証付きURLのホスト部が `:::7144` のようになります。

```
<a data-bind="attr:{href: authUrl}" href="http://:::7144/?auth=aCpZSE9veGNpSTBUcSZ5ODpFaGdtS0pJO0VoZSEyUGFV">リンク</a>
```

ユースケースを考えると、グローバルなIPv6アドレスが入っていて欲しいところですが、難しいですね。

### 動作環境
* OSバージョン: Windows 7 / Ubuntu 18.04.2 LTS
* PeerCastStationバージョン: 2.7.0

**Comment by kumaryu** [comment]
とりあえず直ってるんで閉じときます。
グローバルなIPv6アドレスは判別つかないから難しいかな……
