### ISSUE TITLE
macOS Catalina対応

### ISSUE THREAD

**Issue by madpepper** [kumaryu/peercaststation#427]
MacOSユーザーは此度のCatalinaアップデートで32bitのアプリケーションが実行できなくなりました。自分でビルドし直せばいい話ですが、リリース時にもあるといいです。

**Comment by kumaryu** [comment]
Catalina入れてないのでわかんないんですが、ネイティブなものは使ってないのでmonoが64bitなら64bitで動くはず。
なので64bitとは関係ないんじゃないかという気がするんですけど、どうビルドしなおすと動くんでしょう？

**Comment by kumaryu** [comment]
Monoの6.4でCatalina向けに署名付きバイナリ？になったようです
https://www.mono-project.com/docs/about-mono/releases/6.4.0/
Mono 6.4入れてみたらどうか試してもらえますでしょうか

**Comment by madpepper** [comment]
確かに最新のMono 6.4で動作を確認できました。。。
些細な問題でIssue作ってしまってごめんなさい。

私の方ではIssue閉じても構わないのでよろしくお願いいたします。

**Comment by kumaryu** [comment]
🙆‍♂ 
些細な問題でも知見として貯まるので気軽に報告してください
Catalinaでは6.4以降を使えとどっかに書いときます
