### ISSUE TITLE
2.9.0及び2.9.1でエラー落ちしてしまう。

### ISSUE THREAD

**Issue by nest-peer** [kumaryu/peercaststation#430]
[exception.log](https://github.com/kumaryu/peercaststation/files/3992501/exception.log)
### 問題と期待される動作
(問題の詳細と期待される動作をここに書いてください。
 要望であれば詳しい用途も書いてもらえると対応しやすいです。
 スクリーンショットやファイルは入力欄にドラッグ＆ドロップで添付できます)
### 再現方法
2.9.1アップデート後しばらくは安定していたが再起動後エラーを吐くようになった
再インストールしても同じで復元してもエラーは消えなかった

* OSバージョン:Win8.1 64bit
* .NET Frameworkバージョン: (.NET Frameworkかmonoのバージョンをわかれば書いてください。わからなければ不要です)
* PeerCastStationバージョン:2.9.1及び2.9.0　インストール版
* プレイヤー:PCRP　Ver0.27

**Comment by kumaryu** [comment]
直したのを2.9.2としてリリースしました～

**Comment by nest-peer** [comment]
更新ありがとうございます
今の所ウインドウ動かしてもエラーでず
動いてます
