### ISSUE TITLE
mac/monoでWebから再生ボタンを押すと404になる

### ISSUE THREAD

**Issue by raduwen** [kumaryu/peercaststation#463]
### 問題と期待される動作
リレー(試聴)を開始できない :disappointed_relieved:

### 再現方法

Webから、 `リレー > 適当にチャンネル選択 > 上の再生ボタン` を押す。
新しいタブが開いて、404 となる。

### 動作環境
* OSバージョン: macOS X 11.2.1 (Big Sur)
* Chrome 88.0.4324.150
  * `curl -I http://localhost:7144/pls/xxxxxx?tip=yyyyy` しても404でした
* PeerCastStationバージョン : 以下それぞれ試したものの失敗
  * 2.9.4
  * 2.9.3
  * 2.8.0
* .NET Frameworkバージョン : mono

<details>
<summary>mono latest(6.12.0.107)</summary>

```sh
$ brew install mono
$ mono PeerCastStation.exe
```
</details>

<details>
<summary><a href="https://github.com/Homebrew/homebrew-core/blob/e3e5c4640a/Formula/mono.rb">mono 6.8.0.123</a></summary>

```sh
$ brew unlink mono
$ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
$ git checkout e3e5c4640a mono.rb
$ brew install mono
$ mono PeerCastStation.exe
```
</details>

<details>
<summary><a href="https://github.com/Homebrew/homebrew-core/blob/b4f87c5db3/Formula/mono.rb">mono 6.6.0.161</a></summary>

```sh
$ brew unlink mono
$ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
$ git checkout b4f87c5db3 mono.rb
$ brew install mono
$ mono PeerCastStation.exe
```
</details>

これより古いものは力付きて試してません…

---

先日docker-machineで動かしてみてて、[docker/mono](https://hub.docker.com/_/mono/)でmono:6.12でも同じ現象が起きていた。
mono:6.10だと正常に動いてた気がている。なので、mac BigSurとmonoの何かしらの問題な気がしている。

**Comment by kumaryu** [comment]
72f2d9ca7f1bad875197cccffd6f3291d604cb07 で直ったはず。

monoのバージョンというかいつ発生してもおかしくないのがたまたま今まで出てなかっただけですね。

**Comment by raduwen** [comment]
また今度試してみます！
