### ISSUE TITLE
頻繁にプレイヤーが停止する

### ISSUE THREAD

**Issue by niwakazoider** [kumaryu/peercaststation#464]
### 問題と期待される動作
視聴していると頻繁に再生が止まってしまいます
最初自分の環境のせいかと思いましたがデバッガで確認したところバッファを1秒分しか保持していないように見えます

該当コード？
https://github.com/kumaryu/peercaststation/blob/master/PeerCastStation/PeerCastStation.Core/Content.cs#L123

### 動作環境
* OSバージョン: Windows 10 64bit
* PeerCastStationバージョン: 2.8.0.0 zip版
* プレイヤー: PCRPlayer

**Comment by kumaryu** [comment]
なんでだか忘れたけど1秒にしてあります
そこが問題なのかなあ

**Comment by niwakazoider** [comment]
Peercast YTのバッファを表示する機能でも1秒以下になっていたので
配信者のパケット分割の時点で細かくなりすぎているかも

![peercast-yt](https://user-images.githubusercontent.com/1770418/109064183-6a902f80-772d-11eb-95dd-e9c38e63d84e.png)

**Comment by kumaryu** [comment]
YTはそんなに細かく出るんだ……

確かにパケットの平均サイズが2kは小さいですね。
その辺変えた覚えがあんまりなかったけどどこだろう

**Comment by kumaryu** [comment]
パケットがまとまってなかったんで #465 で対処してみました。

でもビットレートが高いとまとまらないのでもうちょい工夫した方がいいかもなー。

**Comment by kumaryu** [comment]
もうちょっとまとまるようにしてみました

**Comment by niwakazoider** [comment]
対応ありがとうございました
