### ISSUE TITLE
v2.9.5でApplication Errorによるクラッシュが発生する

### ISSUE THREAD

**Issue by aki1-asr** [kumaryu/peercaststation#467]
### 問題と期待される動作

v2.9.5でFLV配信を視聴していたところ、PeerCastStation.exeがApplication Errorでクラッシュしました。
クラッシュ時のWindowsイベントログを添付します。
[pecast_crash.zip](https://github.com/kumaryu/peercaststation/files/6085604/pecast_crash.zip)
なお、ペカステ本体のログはINFOで取得していたものの、そちらには何も出ておりませんでした。

### 再現方法
1696KbpsのFLV配信を50分程視聴したところで1度目のクラッシュが発生しました。
その後ペカステを再起動して視聴を継続したものの、それから丁度4分で再度クラッシュしました。
2度目のクラッシュ時点でペカステを2.9.4に戻したため、それからクラッシュは発生しておりません。

### 動作環境
* OSバージョン: Windows 10 Enterprise LTSC 1809 17763.1790 64bit
* .NET Frameworkバージョン: 4.7.2
* PeerCastStationバージョン: 2.9.5 ZIP版
* プレイヤー: mpv 0.33.0

**Comment by kumaryu** [comment]
GUIでのバッファ情報表示が悪さしてるっぽいですね
修正します
GUI閉じてると起きないかも

**Comment by kumaryu** [comment]
修正した2.9.6をリリースしたので試してみてください

**Comment by aki1-asr** [comment]
2.9.6にしてから数時間視聴しましたが、クラッシュは発生しなくなりました。
ありがとうございました。
