### ISSUE TITLE
v2.9.5で視聴中にクラッシュする

### ISSUE THREAD

**Issue by yudeunagi** [kumaryu/peercaststation#468]
### 問題と期待される動作
v2.9.5でFLV配信を視聴していた際に、PeerCastStationが何の前触れもなく終了しました。
エラーログを以下に添付します。
[exception.log](https://github.com/kumaryu/peercaststation/files/6087062/exception.log)

### 再現方法
1000kbps程度のFLV配信を視聴していたところで1度目のクラッシュが発生。
その後PeerCastStationを起動しなおし視聴を再開したが、20分ほど経過した後に2度目のクラッシュ。
再度起動しなおしたところまた20分ほど経過した後に3度目のクラッシュ。
そのごv2.9.4にバージョンを戻し3時間ほど使用していますが、バージョンを戻してからのクラッシュは発生していません。

### 動作環境
* OSバージョン: Windows 10 Pro 64bit
* .NET Frameworkバージョン: 4.8.03752
* PeerCastStationバージョン: 2.9.5 ZIP版
* プレイヤー:PCRPlayer ver0.26 (2018/06/23)

**Comment by kumaryu** [comment]
#467 と同じっぽいですね。修正します。

**Comment by kumaryu** [comment]
修正した2.9.6をリリースしたので試してみてください

**Comment by yudeunagi** [comment]
v2.9.6にしてから8時間ぐらい使用していますが現在クラッシュは発生しておりません。
ご対応ありがとうございます。
