### ISSUE TITLE
Peercastからリレー要求が来た時にポートチェック要求があってもポートチェックしない

### ISSUE THREAD

**Issue by plonk** [kumaryu/peercaststation#473]
本家 Peercast 系のクライアントが、ポート開放状態のわからないときに Peercast Station で配信されているチャンネルを開いて PCP ハンドシェイク時にポートチェックを要求すると、実際にはポートが開いてなくても非 0 のポート番号が OLEH アトムの下の PORT アトムに設定されて返ってきて、ポート開放済み判定になってしまいます。（YT版とIM版で確認。）

ハンドシェイク時には、クライアント側から HELO アトムが送られて、その子アトムに PORT や PING があるかどうかでポート開放状態が伝達されます。

Peercast は PING を付けるときには PORT もつける挙動になっていますが([servent.cpp](https://github.com/plonk/peercast-yt/blob/96f8dbe5280e0f5047d562255b03c550f1f250ff/core/common/servent.cpp#L1010-L1026))、ペカステは HELO を受け取るときにPORT が付いていると通信相手はポート開放状態だと判断して、PING アトムがあってもチェックを行わない挙動になっています。

https://github.com/kumaryu/peercaststation/blob/3a8eb289f413004ad34368ccc1f891a58263604f/PeerCastStation/PeerCastStation.PCP/PCPOutputStream.cs#L382-L396

そのため、Peercast が送ってくる PING 付き HELO の PORT に設定されているポート番号をそのまま OLEH で返すので、Peercast からはポートチェックが成功したかのように見えてしまいます。

## HELOの小アトムの有無

Peercast:
ファイアウォール状態 | PORT | PING
------------ | ------------- | ------
ON | 無し | 無し
OFF | 有り | 無し
不明 | 有り | 有り

Peercast Station:
ファイアウォール状態 | PORT | PING
------------ | ------------- | ------
ON | 無し | 無し
OFF | 有り | 無し
不明 | 無し | 有り

どうせ同じポート番号が入るので、PING を送るときに PORT まで送る意味はないんですが、互換性のために `(有り, 有り)` でもポートチェックしたほうが良いと思います。

**Comment by kumaryu** [comment]
3.0.0 以降で直ってると思いますので閉じときます。
まだなんかおかしかったら再Openしてください。
