### ISSUE TITLE
www.pecastation.org を HTTPS に

### ISSUE THREAD

**Issue by jyane** [kumaryu/peercaststation#491]
### 問題と期待される動作
最近のインターネット事情としても、Secure でない Web サイトからダウンロードした実行ファイルを気楽に実行できません。
GitHub Pages など独自ドメインであっても HTTPS 対応可能なサービスはあるので、どうにか Secure にできないでしょうか。

### 再現方法
GET https://www.pecastation.org

### 動作環境
N/A

**Comment by kumaryu** [comment]
httpsにすべきだなあとは思ってたけどめんどくさくて後回しになってました。
なんとかしてみます。

それはそれとして、ダウンロードした実行ファイルを実行するのに、ダウンロード経路がHTTPSであることは安全性とはほとんど関係ないと思います。
本来なら実行ファイルだのインストーラだのに署名をつけるのがいいんでしょうけど、証明書がお高い……

**Comment by jyane** [comment]
> ダウンロード経路がHTTPSであることは安全性とはほとんど関係ないと思います。本来なら実行ファイルだのインストーラだのに署名をつけるのがいいんでしょうけど

署名もあれば理想ですね。HTTP での実行ファイルのダウンロードはダウンロード元が不明なので（意図しないサーバーやらへの接続や MITM が起こっている可能性を否定できないので）個人的には不安です。HTTPS だから実行ファイルが安全とは言えないのは確かで、普通に今も Non Secure からダウンロードして使ってるんですけどね

対応いただければありがたいです。よろしくお願いします。

**Comment by kumaryu** [comment]
HTTPS でアクセスできるようにしました。
自動アップデートのダウンロードも HTTPS 経由にしたのですが、古いバージョンの PeerCastStation からのアップデートが上手くいかない場合があるのでなにか対策した方がいいかもしれないですね。

**Comment by kumaryu** [comment]
2.x ではダウンロードも http 経由にするようにしておきました。
3.0 以降は問題ないので https でアップデートされるようになっています。
まあ本当は 2.8 とか新しいのなら https でも大丈夫なんですけど、条件めんどくさいので。
