### ISSUE TITLE
HTTP Direct Connectedが増え続けるだけでストリームが再生されない。

### ISSUE THREAD

**Issue by Sgt-M** [kumaryu/peercaststation#516]
### 問題と期待される動作
3.0.1以降のバージョンで
HTTP Direct Connectedが増え続けるだけでストリームが再生されない。
おそらく増え続けているのはプレイヤーのリトライ動作のたびに増えているようです。
PeerCastStationのGUIから再生が止まっているチャンネルを選択して再接続を押すことでとりあえず再生できる状態に復帰します。
PecaSettings.xmlを削除すると治るというのをみて削除して設定し直しましたが解決しませんでした。
![スクリーンショット 2022-09-27 222604](https://user-images.githubusercontent.com/114493129/192539612-187bb232-f557-48df-98cb-675d922b006b.png)

### 再現方法
確実に再現できる方法は今のところわかりませんが、しばらく視聴していて突然再生が止まったと思ったら発生しています。
リレーが下にぶら下がった状態になるとよく発生しているように見えます。
### 動作環境
* OSバージョン: Windows11 22H2(21H2でも発生)
* .NET Frameworkバージョン: 6.0.9
* PeerCastStationバージョン: 64bitインストーラー版 3.0.1 , 3.1.0 ,  4.0.0 , 5.0.0
* プレイヤー: PCRPlayer 1.00、VLC

[PeercaststationLog.txt](https://github.com/kumaryu/peercaststation/files/9656439/PeercaststationLog.txt)

**Comment by kumaryu** [comment]
調査したメモ:
* HTTP Direct が増えてくのはデータを送信していない間は切断検出がされないので通信エラーにならないせいの模様。
* 上流からデータが降ってこない時に自動的に再接続してる？してるにしても間隔が長すぎるかも。

**Comment by kumaryu** [comment]
#517 でHTTP Directが延々増えていくのは解消されるはず。

**Comment by kumaryu** [comment]
#518 で上流からデータが降ってこない時に再接続しなかったのが直る……かも？

**Comment by Sgt-M** [comment]
5.1.0にアップデートしてから数日間症状が発生していないので無事に直ったようです。
ご対応ありがとうございました。
